Validation: Added msauthor and Table Headers
MicrosoftDocs/bingmaps-docs pull request #226
Opened 2022-05-03 20:19 UTC by kturetz

2022-05-03 20:19 UTC, opbld30 commented
Docs Build status updates of commit _[4319beb](https://github.com/kturetz/bingmaps-docs/commits/4319beb02c17ac5b9691443384238ba753869822)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) | [Details](#user-content-c7c37c83c89deff92b2fd87ca4a747ff-d12c300d)
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) | [Details](#user-content-26c684c29ccab0019cc0baa619a657c3-d12c300d)
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) | [Details](#user-content-98178e63f037961d85672290a0a022ad-d12c300d)
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) | [Details](#user-content-6ce8ed6b483089fb66ceee236bde1201-d12c300d)
[BingMaps/rest-services/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) | [Details](#user-content-8b369dea5e9a3d3ff61d9fc3f33f23b4-d12c300d)
[BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/locations/location-recognition?branch=pr-en-us-226) | [Details](#user-content-9c518ff043354e74098f8ffa543ce352-d12c300d)
[BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights?branch=pr-en-us-226) | [Details](#user-content-efad4302133529c744fa60faddd3935b-d12c300d)
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-226) | [Details](#user-content-6f117dbd61f09b2f20031fb6705694d2-d12c300d)
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-226) | [Details](#user-content-1de30c63f70fad7f4790986e292e2eee-d12c300d)
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-226) | [Details](#user-content-178982884c362d5c3e078e519108d8d4-d12c300d)
[BingMaps/sdk-native/map-control-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-api/index?branch=pr-en-us-226) |

<a id="c7c37c83c89deff92b2fd87ca4a747ff-d12c300d"></a>
### [BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md)
 - **Line 2, Column 1**: **[Warning: ms-author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="26c684c29ccab0019cc0baa619a657c3-d12c300d"></a>
### [BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md)
 - **Line 2, Column 1**: **[Warning: ms-author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="98178e63f037961d85672290a0a022ad-d12c300d"></a>
### [BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md)
 - **Line 2, Column 1**: **[Warning: ms-author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="6ce8ed6b483089fb66ceee236bde1201-d12c300d"></a>
### [BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md)
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="8b369dea5e9a3d3ff61d9fc3f33f23b4-d12c300d"></a>
### [BingMaps/rest-services/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/index.md)
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="9c518ff043354e74098f8ffa543ce352-d12c300d"></a>
### [BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md)
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="efad4302133529c744fa60faddd3935b-d12c300d"></a>
### [BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md)
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review [...]

2022-05-03 22:14 UTC, opbld31 commented
Docs Build status updates of commit _[802ba9e](https://github.com/kturetz/bingmaps-docs/commits/802ba9e9a63f0f1299d98a06a6a9a18c7296d9c8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) | [Details](#user-content-c7c37c83c89deff92b2fd87ca4a747ff-164980ee)
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) | [Details](#user-content-26c684c29ccab0019cc0baa619a657c3-164980ee)
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) | [Details](#user-content-98178e63f037961d85672290a0a022ad-164980ee)
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) |
[BingMaps/rest-services/index.md](https://github.com/kturetz/bingmaps-docs/blob/metadata-msauthor-5-3/BingMaps/rest-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) |
[BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/locations/location-recognition?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-226) |
[BingMaps/sdk-native/map-control-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-api/index?branch=pr-en-us-226) |

<a id="c7c37c83c89deff92b2fd87ca4a747ff-164980ee"></a>
### [BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md)
 - **Line 2, Column 1**: **[Warning: ms-author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="26c684c29ccab0019cc0baa619a657c3-164980ee"></a>
### [BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md)
 - **Line 2, Column 1**: **[Warning: ms-author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="98178e63f037961d85672290a0a022ad-164980ee"></a>
### [BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md)
 - **Line 2, Column 1**: **[Warning: ms-author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5C587a3825-77bd-8a4b-21c8-e8662dbef49c%5CPullRequest%5C202205032213386192-226%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T22%3A14%3A36Z&sr=b&sp=r&sig=dP%2B2s2PeG6V%2BgH7P9b5j1AUHbVFVytARH6itKko0f38%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 16:22 UTC, opbld31 commented
Docs Build status updates of commit _[5aef361](https://github.com/kturetz/bingmaps-docs/commits/5aef3611d4840c48eff4d49d01a7ee621db4c182)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) | [Details](#user-content-c7c37c83c89deff92b2fd87ca4a747ff-7498329b)
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-226) | [Details](#user-content-67dde7795c4ac99dbb59e187eafb68b5-7498329b)
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) | [Details](#user-content-26c684c29ccab0019cc0baa619a657c3-7498329b)
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) | [Details](#user-content-98178e63f037961d85672290a0a022ad-7498329b)
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-226) | [Details](#user-content-99093358059c624fd9689ae552849ec4-7498329b)
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-226) | [Details](#user-content-dd6780c4dc1f8888e8e2ae239cf015fd-7498329b)
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-226) | [Details](#user-content-3b540ec6b732e096901247770e720565-7498329b)
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-226) | [Details](#user-content-63e27e0ed98097318737ba867d1c03ae-7498329b)
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-226) | [Details](#user-content-e196b363c395ddb8b78e0a070e8de9f3-7498329b)
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-226) | [Details](#user-content-8c9d80b823cc46c0f3cc739693a854e4-7498329b)
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-226) | [Details](#user-content-c1bdc3455bd82855564cf218ed3bc3c9-7498329b)
[BingMaps/venues/address.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/address.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/address?branch=pr-en-us-226) | [Details](#user-content-38dc56a32f45673687c30a0f021eac58-7498329b)
[BingMaps/venues/entity.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/entity.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/entity?branch=pr-en-us-226) | [Details](#user-content-6a6da3ec28a2655f33702397cd477379-7498329b)
[BingMaps/venues/floor.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/floor.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/floor?branch=pr-en-us-226) | [Details](#user-content-b68d21c55df51b9a1888c8ed51c05cc9-7498329b)
[BingMaps/venues/geometry.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/geometry.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/geometry?branch=pr-en-us-226) | [Details](#user-content-3c06d35c2b797828f4e273455fb76cf6-7498329b)
[BingMaps/venues/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/index?branch=pr-en-us-226) | [Details](#user-content-24569a7ad82feb58c6bccf0c26670c84-7498329b)
[BingMaps/venues/inner.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/inner.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/inner?branch=pr-en-us-226) | [Details](#user-content-991352a76abf3cc38c04550b5e736226-7498329b)
[BingMaps/venues/label.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/label.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/label?branch=pr-en-us-226) | [Details](#user-content-fee4256d940d261ddd846925a936927f-7498329b)
[BingMaps/venues/rectangle.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/rectangle.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/rectangle?branch=pr-en-us-226) | [Details](#user-content-4abd06f9404ac32f3a722bb0bf3a2470-7498329b)
[BingMaps/venues/sample.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/sample.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/sample?branch=pr-en-us-226) | [Details](#user-content-d55aa97901d0fa730aeba82024281a74-7498329b)
[BingMaps/venues/venue.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/venue.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/venue?branch=pr-en-us-226) | [Details](#user-content-89eec24a0f86aaf67e7c6378ba3e5daa-7498329b)
[BingMaps/venues/venueTile.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/venueTile.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/venuetile?branch=pr-en-us-226) | [Details](#user-content-60d0cf8f50f0383ed381159e1b1b7c30-7498329b)
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) |
[BingMaps/rest-services/index.md](https://github.com/kturetz/bingmaps-docs/blob/metadata-msauthor-5-3/BingMaps/rest-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) |
[BingMaps/rest-services/locations/location-re [...]

2022-05-04 17:35 UTC, opbld32 commented
Docs Build status updates of commit _[2bbc62f](https://github.com/kturetz/bingmaps-docs/commits/2bbc62fb4538815066bc51dfd20c25c2d806ef6a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) | [Details](#user-content-c7c37c83c89deff92b2fd87ca4a747ff-a9c4f802)
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-226) | [Details](#user-content-67dde7795c4ac99dbb59e187eafb68b5-a9c4f802)
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) | [Details](#user-content-26c684c29ccab0019cc0baa619a657c3-a9c4f802)
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) | [Details](#user-content-98178e63f037961d85672290a0a022ad-a9c4f802)
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-226) | [Details](#user-content-8c9d80b823cc46c0f3cc739693a854e4-a9c4f802)
[BingMaps/venues/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/index?branch=pr-en-us-226) | [Details](#user-content-24569a7ad82feb58c6bccf0c26670c84-a9c4f802)
[BingMaps/venues/inner.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/inner.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/inner?branch=pr-en-us-226) | [Details](#user-content-991352a76abf3cc38c04550b5e736226-a9c4f802)
[BingMaps/venues/label.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/label.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/label?branch=pr-en-us-226) | [Details](#user-content-fee4256d940d261ddd846925a936927f-a9c4f802)
[BingMaps/venues/rectangle.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/rectangle.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/rectangle?branch=pr-en-us-226) | [Details](#user-content-4abd06f9404ac32f3a722bb0bf3a2470-a9c4f802)
[BingMaps/venues/sample.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/sample.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/sample?branch=pr-en-us-226) | [Details](#user-content-d55aa97901d0fa730aeba82024281a74-a9c4f802)
[BingMaps/venues/venue.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/venue.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/venue?branch=pr-en-us-226) | [Details](#user-content-89eec24a0f86aaf67e7c6378ba3e5daa-a9c4f802)
[BingMaps/venues/venueTile.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/venueTile.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/venuetile?branch=pr-en-us-226) | [Details](#user-content-60d0cf8f50f0383ed381159e1b1b7c30-a9c4f802)
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) |
[BingMaps/rest-services/index.md](https://github.com/kturetz/bingmaps-docs/blob/metadata-msauthor-5-3/BingMaps/rest-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) |
[BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/locations/location-recognition?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-226) |
[BingMaps/sdk-native/map-control-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-api/index?branch=pr-en-us-226) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sty [...]

2022-05-04 18:26 UTC, opbld30 commented
Docs Build status updates of commit _[d6f255d](https://github.com/kturetz/bingmaps-docs/commits/d6f255d54ecf4d39715ef7d2302c4521d1230163)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) | [Details](#user-content-c7c37c83c89deff92b2fd87ca4a747ff-02bebf61)
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) | [Details](#user-content-26c684c29ccab0019cc0baa619a657c3-02bebf61)
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) | [Details](#user-content-98178e63f037961d85672290a0a022ad-02bebf61)
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) |
[BingMaps/rest-services/index.md](https://github.com/kturetz/bingmaps-docs/blob/metadata-msauthor-5-3/BingMaps/rest-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) |
[BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/locations/location-recognition?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-226) |
[BingMaps/sdk-native/map-control-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-api/index?branch=pr-en-us-226) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-226) |
[BingMaps/venues/address.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/address.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/address?branch=pr-en-us-226) |
[BingMaps/venues/entity.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/entity?branch=pr-en-us-226) |
[BingMaps/venues/floor.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/floor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/floor?branch=pr-en-us-226) |
[BingMaps/venues/geometry.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/geometry.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/geometry?branch=pr-en-us-226) |
[BingMaps/venues/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/index?branch=pr-en-us-226) |
[BingMaps/venues/inner.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/inner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/inner?branch=pr-en-us-226) |

This comment lists only the first 25 files in the pull request.
<a id="c7c37c83c89deff92b2fd87ca4a747ff-02bebf61"></a>
### [BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md)
 - **Line 2, Column 1**: **[Warning: ms-author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/valid [...]

2022-05-04 19:04 UTC, kturetz commented
@stevemunk 
@rbrundritt 
@DavidBuerer
@yasong-Ashley 
@jesselgit 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-01 00:32 UTC, opbld31 commented
Docs Build status updates of commit _[b2e5dc5](https://github.com/kturetz/bingmaps-docs/commits/b2e5dc5b13cef5053dbfae14e9aa77ad9991ec2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) |
[BingMaps/rest-services/index.md](https://github.com/kturetz/bingmaps-docs/blob/metadata-msauthor-5-3/BingMaps/rest-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) |
[BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/locations/location-recognition?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) |
[BingMaps/sdk-native/map-control-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-api/index?branch=pr-en-us-226) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-226) |
[BingMaps/venues/address.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/address.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/address?branch=pr-en-us-226) |
[BingMaps/venues/entity.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/entity?branch=pr-en-us-226) |
[BingMaps/venues/floor.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/floor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/floor?branch=pr-en-us-226) |
[BingMaps/venues/geometry.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/geometry.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/geometry?branch=pr-en-us-226) |
[BingMaps/venues/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/index?branch=pr-en-us-226) |
[BingMaps/venues/inner.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/inner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/inner?branch=pr-en-us-226) |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206010031141153-226/BuildReport?accessString=0bac024a261cfc25336e69c2154533cb9a162b78774e23dee6cedfcc1f95b89f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName [...]

2022-06-04 00:17 UTC, stevemunk requested changes

2022-06-04 00:17 UTC, stevemunk commented on BingMaps/styling/map-style-sheet-entries.md
> +description: The entries listed below can be used in a map style sheet to customize the appearance of a map in various Microsoft map controls.
```suggestion
description: A list of settings and elements that can be used in a map style sheet to customize the appearance of a map in various Microsoft map controls. They can also be used to define how overlaid geometry on a map should be represented.
```

2022-06-04 00:17 UTC, stevemunk commented on BingMaps/styling/map-style-sheet-entry-properties.md
> +description: The properties listed below can be set on entries in a map style sheet to customize the appearance of a map in various Microsoft map controls.
```suggestion
description: Learn about the map style sheet entry properties that can be set on entries in a map style sheet to customize the maps appearance in various Microsoft map controls.
```

2022-06-04 00:17 UTC, stevemunk commented on BingMaps/styling/map-style-sheet-support.md
> +description: Map styling can be applied to a variety of Microsoft map controls, including Bing Maps, Static, Windows, Android, or iOS.
```suggestion
description: Learn about map styles supported in a variety of Microsoft map controls with a list showing the controls that support it, a link to the Map Style Sheet Editor application and a table showing the minimum version of each control that supports each style version.
```

2022-06-04 16:27 UTC, opbld30 commented
Docs Build status updates of commit _[1ae7ca4](https://github.com/kturetz/bingmaps-docs/commits/1ae7ca4e42a0b0108f11e47b7e3cc91ae5622dbe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) |
[BingMaps/rest-services/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) |
[BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/locations/location-recognition?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) |
[BingMaps/sdk-native/map-control-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-api/index?branch=pr-en-us-226) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-226) |
[BingMaps/venues/address.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/address.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/address?branch=pr-en-us-226) |
[BingMaps/venues/entity.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/entity?branch=pr-en-us-226) |
[BingMaps/venues/floor.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/floor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/floor?branch=pr-en-us-226) |
[BingMaps/venues/geometry.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/geometry.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/geometry?branch=pr-en-us-226) |
[BingMaps/venues/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/index?branch=pr-en-us-226) |
[BingMaps/venues/inner.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/inner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/inner?branch=pr-en-us-226) |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206041626186609-226/BuildReport?accessString=21029b412b1c5a06b98524a3b4eedfe6058efe9e5231121d1871859926cbfbf1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlink [...]

2022-06-04 16:28 UTC, opbld30 commented
Docs Build status updates of commit _[b61a3d3](https://github.com/kturetz/bingmaps-docs/commits/b61a3d3e6852c4b4dfa8a12dc175356a1cde8394)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) |
[BingMaps/rest-services/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) |
[BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/locations/location-recognition?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) |
[BingMaps/sdk-native/map-control-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-api/index?branch=pr-en-us-226) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-226) |
[BingMaps/venues/address.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/address.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/address?branch=pr-en-us-226) |
[BingMaps/venues/entity.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/entity?branch=pr-en-us-226) |
[BingMaps/venues/floor.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/floor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/floor?branch=pr-en-us-226) |
[BingMaps/venues/geometry.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/geometry.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/geometry?branch=pr-en-us-226) |
[BingMaps/venues/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/index?branch=pr-en-us-226) |
[BingMaps/venues/inner.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/inner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/inner?branch=pr-en-us-226) |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206041626439144-226/BuildReport?accessString=30e17bc2971b01d1e38f98ca8fefa8936a2f0b9da6f3c6d734d7f2cd0ffcb54d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlink [...]

2022-06-04 16:30 UTC, opbld30 commented
Docs Build status updates of commit _[043dd18](https://github.com/kturetz/bingmaps-docs/commits/043dd18414692dbf99301b427143693fb8062224)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) |
[BingMaps/rest-services/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) |
[BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/locations/location-recognition?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) |
[BingMaps/sdk-native/map-control-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-api/index?branch=pr-en-us-226) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-226) |
[BingMaps/venues/address.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/address.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/address?branch=pr-en-us-226) |
[BingMaps/venues/entity.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/entity?branch=pr-en-us-226) |
[BingMaps/venues/floor.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/floor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/floor?branch=pr-en-us-226) |
[BingMaps/venues/geometry.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/geometry.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/geometry?branch=pr-en-us-226) |
[BingMaps/venues/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/index?branch=pr-en-us-226) |
[BingMaps/venues/inner.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/inner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/inner?branch=pr-en-us-226) |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206041627528899-226/BuildReport?accessString=473b219c5c2c8011282435bb1f9b42ae2e3a485c72513df619585a9c5f6af963).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlink [...]

2022-06-04 16:31 UTC, opbld33 commented
Docs Build status updates of commit _[faa29b7](https://github.com/kturetz/bingmaps-docs/commits/faa29b79823fb429edbb440fa5a4503f2b8b7aca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) |
[BingMaps/rest-services/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) |
[BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/locations/location-recognition?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) |
[BingMaps/sdk-native/map-control-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-api/index?branch=pr-en-us-226) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-226) |
[BingMaps/venues/address.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/address.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/address?branch=pr-en-us-226) |
[BingMaps/venues/entity.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/entity?branch=pr-en-us-226) |
[BingMaps/venues/floor.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/floor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/floor?branch=pr-en-us-226) |
[BingMaps/venues/geometry.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/geometry.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/geometry?branch=pr-en-us-226) |
[BingMaps/venues/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/index?branch=pr-en-us-226) |
[BingMaps/venues/inner.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/inner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/inner?branch=pr-en-us-226) |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206041627430492-226/BuildReport?accessString=56cd6ea7ffa585182b2e68b2ba70a980c5f2368978aa8ef659d9a74a3783de8a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlink [...]

2022-06-04 16:32 UTC, opbld31 commented
Docs Build status updates of commit _[8687e50](https://github.com/kturetz/bingmaps-docs/commits/8687e5072ba3a6eae029bf574af325e1a1d93f87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) |
[BingMaps/rest-services/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) |
[BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/locations/location-recognition?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) |
[BingMaps/sdk-native/map-control-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-api/index?branch=pr-en-us-226) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-226) |
[BingMaps/venues/address.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/address.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/address?branch=pr-en-us-226) |
[BingMaps/venues/entity.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/entity?branch=pr-en-us-226) |
[BingMaps/venues/floor.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/floor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/floor?branch=pr-en-us-226) |
[BingMaps/venues/geometry.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/geometry.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/geometry?branch=pr-en-us-226) |
[BingMaps/venues/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/index?branch=pr-en-us-226) |
[BingMaps/venues/inner.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/inner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/inner?branch=pr-en-us-226) |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206041628396577-226/BuildReport?accessString=776813182cf9220154c8c350c0f0edff91d75fe5f9a5bd4c0a267a1fe80c5b2b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlink [...]

2022-06-04 16:33 UTC, opbld33 commented
Docs Build status updates of commit _[fe0da63](https://github.com/kturetz/bingmaps-docs/commits/fe0da639e7c4898bbbdb3631ee43638978806fa0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) |
[BingMaps/rest-services/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) |
[BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/locations/location-recognition?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) |
[BingMaps/sdk-native/map-control-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-api/index?branch=pr-en-us-226) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-226) |
[BingMaps/venues/address.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/address.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/address?branch=pr-en-us-226) |
[BingMaps/venues/entity.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/entity?branch=pr-en-us-226) |
[BingMaps/venues/floor.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/floor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/floor?branch=pr-en-us-226) |
[BingMaps/venues/geometry.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/geometry.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/geometry?branch=pr-en-us-226) |
[BingMaps/venues/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/index?branch=pr-en-us-226) |
[BingMaps/venues/inner.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/inner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/inner?branch=pr-en-us-226) |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206041629052915-226/BuildReport?accessString=04c6d4573b466421dec177027c82a8025193ea6544631121563f6f0774965b3c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlink [...]

2022-06-04 16:34 UTC, opbld33 commented
Docs Build status updates of commit _[f0d3016](https://github.com/kturetz/bingmaps-docs/commits/f0d301619d24708b6812d3b169bb2a7f8398f5b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) |
[BingMaps/rest-services/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) |
[BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/locations/location-recognition?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) |
[BingMaps/sdk-native/map-control-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-api/index?branch=pr-en-us-226) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-226) |
[BingMaps/venues/address.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/address.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/address?branch=pr-en-us-226) |
[BingMaps/venues/entity.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/entity?branch=pr-en-us-226) |
[BingMaps/venues/floor.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/floor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/floor?branch=pr-en-us-226) |
[BingMaps/venues/geometry.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/geometry.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/geometry?branch=pr-en-us-226) |
[BingMaps/venues/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/index?branch=pr-en-us-226) |
[BingMaps/venues/inner.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/inner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/inner?branch=pr-en-us-226) |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206041629565997-226/BuildReport?accessString=182abad25fdbc65bb146c0654e9f70505bc15a81374de3d8dedd4ef4cbde2f21).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlink [...]

2022-06-06 19:26 UTC, stevemunk approved these changes

2022-06-06 19:28 UTC, opbld30 commented
Docs Build status updates of commit _[ec8db1f](https://github.com/kturetz/bingmaps-docs/commits/ec8db1fff4721b838da7413620da4e4473411378)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/articles/open-maps-understanding-odbl?branch=pr-en-us-226) | [Details](#user-content-6ce8ed6b483089fb66ceee236bde1201-43cbbd68)
[BingMaps/rest-services/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/index?branch=pr-en-us-226) |
[BingMaps/rest-services/locations/location-recognition.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/locations/location-recognition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/locations/location-recognition?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/local-insights.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/local-insights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/local-insights?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-226) |
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-226) |
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-226) |
[BingMaps/sdk-native/map-control-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-api/index?branch=pr-en-us-226) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-226) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-226) |
[BingMaps/venues/address.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/address.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/address?branch=pr-en-us-226) |
[BingMaps/venues/entity.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/entity?branch=pr-en-us-226) |
[BingMaps/venues/floor.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/floor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/floor?branch=pr-en-us-226) |
[BingMaps/venues/geometry.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/geometry.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/geometry?branch=pr-en-us-226) |
[BingMaps/venues/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/index?branch=pr-en-us-226) |
[BingMaps/venues/inner.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/inner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/inner?branch=pr-en-us-226) |

This comment lists only the first 25 files in the pull request.
<a id="6ce8ed6b483089fb66ceee236bde1201-43cbbd68"></a>
### [BingMaps/articles/open-maps-understanding-odbl.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/articles/open-maps-understanding-odbl.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results [...]

2022-06-06 19:36 UTC, merged