Validation: description-missing fixes.
MicrosoftDocs/bingmaps-docs pull request #232
Opened 2022-05-24 17:29 UTC by brittmsantos

Adds missing descriptions to fix validation errors.

2022-05-24 17:34 UTC, opbld30 commented
Docs Build status updates of commit _[6d70767](https://github.com/brittmsantos/bingmaps-docs/commits/6d707674c99825dbcc49087b207b037686d272c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/venues/address.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/address.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/address?branch=pr-en-us-232) | [Details](#user-content-38dc56a32f45673687c30a0f021eac58-b16700be)
[BingMaps/venues/entity.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/entity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/entity?branch=pr-en-us-232) | [Details](#user-content-6a6da3ec28a2655f33702397cd477379-b16700be)
[BingMaps/venues/floor.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/floor.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/floor?branch=pr-en-us-232) | [Details](#user-content-b68d21c55df51b9a1888c8ed51c05cc9-b16700be)
[BingMaps/venues/geometry.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/geometry.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/geometry?branch=pr-en-us-232) | [Details](#user-content-3c06d35c2b797828f4e273455fb76cf6-b16700be)
[BingMaps/venues/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/index?branch=pr-en-us-232) | [Details](#user-content-24569a7ad82feb58c6bccf0c26670c84-b16700be)
[BingMaps/venues/inner.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/inner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/inner?branch=pr-en-us-232) | [Details](#user-content-991352a76abf3cc38c04550b5e736226-b16700be)
[BingMaps/venues/label.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/label.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/label?branch=pr-en-us-232) | [Details](#user-content-fee4256d940d261ddd846925a936927f-b16700be)
[BingMaps/venues/rectangle.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/rectangle.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/rectangle?branch=pr-en-us-232) | [Details](#user-content-4abd06f9404ac32f3a722bb0bf3a2470-b16700be)
[BingMaps/venues/sample.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/sample.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/sample?branch=pr-en-us-232) | [Details](#user-content-d55aa97901d0fa730aeba82024281a74-b16700be)
[BingMaps/venues/venue.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/venue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/venue?branch=pr-en-us-232) | [Details](#user-content-89eec24a0f86aaf67e7c6378ba3e5daa-b16700be)
[BingMaps/venues/venueTile.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/venueTile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/venuetile?branch=pr-en-us-232) | [Details](#user-content-60d0cf8f50f0383ed381159e1b1b7c30-b16700be)
[BingMaps/v8-web-control/modules/venue-map-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/index?branch=pr-en-us-232) | [Details](#user-content-4f30257a40005b43f557eccea1ba5f56-b16700be)
[BingMaps/v8-web-control/modules/venue-map-module/venuemap-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/venuemap-class.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/venuemap-class?branch=pr-en-us-232) | [Details](#user-content-1e39247aab6082cde31c93e680e10391-b16700be)
[BingMaps/v8-web-control/modules/venue-map-module/venuemapfactory-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/venuemapfactory-class.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/venuemapfactory-class?branch=pr-en-us-232) | [Details](#user-content-a1c01938d03c523a09bb541f5176a964-b16700be)
[BingMaps/v8-web-control/modules/venue-map-module/venuemapoptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/venuemapoptions-object.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/venuemapoptions-object?branch=pr-en-us-232) | [Details](#user-content-a72de6123f50c9765ba059d2d21a2add-b16700be)
[BingMaps/v8-web-control/modules/well-known-text-module.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/well-known-text-module.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/well-known-text-module?branch=pr-en-us-232) | [Details](#user-content-8fad4d53688d1f8eb9cfc9f05ade7bc5-b16700be)
[BingMaps/v8-web-control/modules/spatial-data-service-module/queryapimanager-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapimanager-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapimanager-class?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/queryapioptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapioptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapioptions-object?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/spatialfilteroptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/spatialfilteroptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/spatialfilteroptions-object?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/areaunits-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/areaunits-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/areaunits-enumeration?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/bufferendcap-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/bufferendcap-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/bufferendcap-enumeration?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/core-calculations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/core-calculations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/core-calculations?branch=pr-en-us-232) [...]

2022-05-24 18:32 UTC, opbld31 commented
Docs Build status updates of commit _[f7d8386](https://github.com/brittmsantos/bingmaps-docs/commits/f7d838602b135c2ae24fe1d47c523a5d1f1643bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/v8-web-control/modules/venue-map-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/index?branch=pr-en-us-232) | [Details](#user-content-4f30257a40005b43f557eccea1ba5f56-6f6223b4)
[BingMaps/v8-web-control/modules/venue-map-module/venuemap-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/venuemap-class.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/venuemap-class?branch=pr-en-us-232) | [Details](#user-content-1e39247aab6082cde31c93e680e10391-6f6223b4)
[BingMaps/v8-web-control/modules/venue-map-module/venuemapfactory-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/venuemapfactory-class.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/venuemapfactory-class?branch=pr-en-us-232) | [Details](#user-content-a1c01938d03c523a09bb541f5176a964-6f6223b4)
[BingMaps/v8-web-control/modules/venue-map-module/venuemapoptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/venuemapoptions-object.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/venuemapoptions-object?branch=pr-en-us-232) | [Details](#user-content-a72de6123f50c9765ba059d2d21a2add-6f6223b4)
[BingMaps/v8-web-control/modules/spatial-data-service-module/queryapimanager-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapimanager-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapimanager-class?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/queryapioptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapioptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapioptions-object?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/spatialfilteroptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/spatialfilteroptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/spatialfilteroptions-object?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/areaunits-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/areaunits-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/areaunits-enumeration?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/bufferendcap-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/bufferendcap-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/bufferendcap-enumeration?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/core-calculations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/core-calculations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/core-calculations?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/distanceunits-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/distanceunits-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/distanceunits-enumeration?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/geometry-calculations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/geometry-calculations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/geometry-calculations?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/index?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/tile-calculations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/tile-calculations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/tile-calculations?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/traffic-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/traffic-module/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/traffic-module/index?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/traffic-module/trafficmanager-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/traffic-module/trafficmanager-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/traffic-module/trafficmanager-class?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/traffic-module/trafficoptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/traffic-module/trafficoptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/traffic-module/trafficoptions-object?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/well-known-text-module.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/well-known-text-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/well-known-text-module?branch=pr-en-us-232) |
[BingMaps/v8-web-control/supported-browsers.md](https://github.com/brittmsantos/bingmaps-docs/blob/BMPR1-5-24/BingMaps/v8-web-control/supported-browsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/supported-browsers?branch=pr-en-us-232) |
[BingMaps/venues/address.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/address.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/venues/address?branch=pr-en-us-232) |
[BingMaps/venues/entity.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/venues/entity.md) | :white_check_mark:Succeeded | [View](ht [...]

2022-06-06 20:14 UTC, opbld30 commented
Docs Build status updates of commit _[1065c7b](https://github.com/brittmsantos/bingmaps-docs/commits/1065c7bbb55a8e519473f51935f2a4a6205606d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/v8-web-control/modules/venue-map-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/index?branch=pr-en-us-232) | [Details](#user-content-4f30257a40005b43f557eccea1ba5f56-0dc13d46)
[BingMaps/v8-web-control/modules/venue-map-module/venuemap-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/venuemap-class.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/venuemap-class?branch=pr-en-us-232) | [Details](#user-content-1e39247aab6082cde31c93e680e10391-0dc13d46)
[BingMaps/v8-web-control/modules/venue-map-module/venuemapfactory-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/venuemapfactory-class.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/venuemapfactory-class?branch=pr-en-us-232) | [Details](#user-content-a1c01938d03c523a09bb541f5176a964-0dc13d46)
[BingMaps/v8-web-control/modules/venue-map-module/venuemapoptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/venuemapoptions-object.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/venuemapoptions-object?branch=pr-en-us-232) | [Details](#user-content-a72de6123f50c9765ba059d2d21a2add-0dc13d46)
[BingMaps/v8-web-control/modules/spatial-data-service-module/queryapimanager-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapimanager-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapimanager-class?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/queryapioptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapioptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapioptions-object?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/spatialfilteroptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/spatialfilteroptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/spatialfilteroptions-object?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/areaunits-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/areaunits-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/areaunits-enumeration?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/bufferendcap-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/bufferendcap-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/bufferendcap-enumeration?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/core-calculations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/core-calculations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/core-calculations?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/distanceunits-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/distanceunits-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/distanceunits-enumeration?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/geometry-calculations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/geometry-calculations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/geometry-calculations?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/index?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/tile-calculations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/tile-calculations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/tile-calculations?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/traffic-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/traffic-module/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/traffic-module/index?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/traffic-module/trafficmanager-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/traffic-module/trafficmanager-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/traffic-module/trafficmanager-class?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/traffic-module/trafficoptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/traffic-module/trafficoptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/traffic-module/trafficoptions-object?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/well-known-text-module.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/well-known-text-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/well-known-text-module?branch=pr-en-us-232) |
[BingMaps/v8-web-control/supported-browsers.md](https://github.com/brittmsantos/bingmaps-docs/blob/BMPR1-5-24/BingMaps/v8-web-control/supported-browsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/supported-browsers?branch=pr-en-us-232) |

<a id="4f30257a40005b43f557eccea1ba5f56-0dc13d46"></a>
### [BingMaps/v8-web-control/modules/venue-map-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/index.md)
 - **Line 13, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-a [...]

2022-06-06 21:09 UTC, stevemunk requested changes

2022-06-06 21:09 UTC, stevemunk commented on BingMaps/v8-web-control/modules/venue-map-module/venuemapfactory-class.md
> +description: Describes the Venue Maps factory class, which creates instances of the VenueMap class, and details its constructor and methods.
```suggestion
description: Describes the Venue Maps factory class, which creates instances of the VenueMap class, and details its constructor and create method.
```

2022-06-06 21:09 UTC, stevemunk commented on BingMaps/v8-web-control/modules/venue-map-module/venuemapoptions-object.md
> +description: Describes the VenueMapsOptions object and details its properties and the VenueMapMetadataLoader method.
```suggestion
description: Describes the VenueMapsOptions object that is used to customize how a Venue file is read and loaded via the VenueMapFactory and details its properties and the VenueMapMetadataLoader method.
```

2022-06-07 14:14 UTC, opbld31 commented
Docs Build status updates of commit _[884d573](https://github.com/brittmsantos/bingmaps-docs/commits/884d57342c74bf0221759767ae097bdd5cd50d34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/v8-web-control/modules/venue-map-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/index?branch=pr-en-us-232) | [Details](#user-content-4f30257a40005b43f557eccea1ba5f56-e263e722)
[BingMaps/v8-web-control/modules/venue-map-module/venuemap-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/venuemap-class.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/venuemap-class?branch=pr-en-us-232) | [Details](#user-content-1e39247aab6082cde31c93e680e10391-e263e722)
[BingMaps/v8-web-control/modules/venue-map-module/venuemapfactory-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/venuemapfactory-class.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/venuemapfactory-class?branch=pr-en-us-232) | [Details](#user-content-a1c01938d03c523a09bb541f5176a964-e263e722)
[BingMaps/v8-web-control/modules/venue-map-module/venuemapoptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/venuemapoptions-object.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/venue-map-module/venuemapoptions-object?branch=pr-en-us-232) | [Details](#user-content-a72de6123f50c9765ba059d2d21a2add-e263e722)
[BingMaps/v8-web-control/modules/spatial-data-service-module/queryapimanager-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapimanager-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapimanager-class?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/queryapioptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapioptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/queryapioptions-object?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/spatialfilteroptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/spatialfilteroptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/spatialfilteroptions-object?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/areaunits-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/areaunits-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/areaunits-enumeration?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/bufferendcap-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/bufferendcap-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/bufferendcap-enumeration?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/core-calculations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/core-calculations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/core-calculations?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/distanceunits-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/distanceunits-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/distanceunits-enumeration?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/geometry-calculations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/geometry-calculations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/geometry-calculations?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/index?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/spatial-math-module/tile-calculations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-math-module/tile-calculations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-math-module/tile-calculations?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/traffic-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/traffic-module/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/traffic-module/index?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/traffic-module/trafficmanager-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/traffic-module/trafficmanager-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/traffic-module/trafficmanager-class?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/traffic-module/trafficoptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/traffic-module/trafficoptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/traffic-module/trafficoptions-object?branch=pr-en-us-232) |
[BingMaps/v8-web-control/modules/well-known-text-module.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/well-known-text-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/well-known-text-module?branch=pr-en-us-232) |
[BingMaps/v8-web-control/supported-browsers.md](https://github.com/brittmsantos/bingmaps-docs/blob/BMPR1-5-24/BingMaps/v8-web-control/supported-browsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/supported-browsers?branch=pr-en-us-232) |

<a id="4f30257a40005b43f557eccea1ba5f56-e263e722"></a>
### [BingMaps/v8-web-control/modules/venue-map-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/venue-map-module/index.md)
 - **Line 13, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-a [...]

2022-06-07 14:18 UTC, brittmsantos commented
@stevemunk

I've implemented the requested changes. Please let me know if there are any other issues preventing approval and merge. Thanks!

2022-06-07 19:36 UTC, merged