Validation: Description-missing fixes.
MicrosoftDocs/bingmaps-docs pull request #234
Opened 2022-05-25 22:00 UTC by brittmsantos

Added missing descriptions to fix validation errors.

2022-05-25 22:02 UTC, opbld33 commented
Docs Build status updates of commit _[9388492](https://github.com/brittmsantos/bingmaps-docs/commits/9388492215550a29a8dfff3886d52d8731b363d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/v8-web-control/modules/directions-module/routeoptimization-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/directions-module/routeoptimization-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/directions-module/routeoptimization-enumeration?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/geoxml-module/kmlscreenoverlayoptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/geoxml-module/kmlscreenoverlayoptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/geoxml-module/kmlscreenoverlayoptions-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/heat-map-module/heatmaplayer-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/heat-map-module/heatmaplayer-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/heat-map-module/heatmaplayer-class?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/heat-map-module/heatmaplayeroptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/heat-map-module/heatmaplayeroptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/heat-map-module/heatmaplayeroptions-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/heat-map-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/heat-map-module/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/heat-map-module/index?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/index?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/address-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/address-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/address-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/geocodelocation-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/geocodelocation-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/geocodelocation-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/geocoderequestoptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/geocoderequestoptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/geocoderequestoptions-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/geocoderesult-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/geocoderesult-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/geocoderesult-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/index?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/matchcode-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/matchcode-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/matchcode-enumeration?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/matchconfidence-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/matchconfidence-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/matchconfidence-enumeration?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/placeresult-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/placeresult-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/placeresult-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/reversegeocoderequestoptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/reversegeocoderequestoptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/reversegeocoderequestoptions-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/searchmanager-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/searchmanager-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/searchmanager-class?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/copyright-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/copyright-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/copyright-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/copyrightsource-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/copyrightsource-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/copyrightsource-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/filter-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/filter-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/filter-class?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/filtercompareoperator-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/filtercompareoperator-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/filtercompareoperator-enumeration?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/filtergroup-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spa [...]

2022-05-25 22:17 UTC, brittmsantos commented
@stevemunk @rbrundritt

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-07 19:28 UTC, stevemunk requested changes

2022-06-07 19:28 UTC, stevemunk commented on BingMaps/v8-web-control/modules/spatial-data-service-module/geodataresult-object.md
> +description: Describes the GeoDataResult object, which represents a single result GeoData API object, and provides its properties.
```suggestion
description: Describes the GeoDataResult object, which represents a single result GeoData API object, and includes descriptions for each of its properties.
```

2022-06-07 19:28 UTC, stevemunk commented on BingMaps/v8-web-control/modules/spatial-data-service-module/getboundaryrequestoptions-object.md
> +description: Describes the GetBoundaryRequestOptions object, which contains the options for GeoData API requests boundary data, and provides its properties.
```suggestion
description: Describes the GetBoundaryRequestOptions object, which contains the options for GeoData API requests boundary data, with descriptions for each of its properties.
```

2022-06-07 19:28 UTC, stevemunk commented on BingMaps/v8-web-control/modules/spatial-data-service-module/index.md
> +description: Describes the Spatial Data Service module, which allows uploading data to expose as a spatial REST service for applications.
```suggestion
description: The overview page for the Spatial Data Service module, which allows uploading data to expose as a spatial REST service for applications, with links to articles that describe the various classes, enumerators, a filter example and several more examples demonstrating both the Query and GeoData API.
```

2022-06-08 17:42 UTC, brittmsantos commented
@stevemunk 

I've implemented the requested changes. Please let me know if there are any other issues preventing approval and merge. Thank you and have a great day!

2022-06-08 17:43 UTC, opbld30 commented
Docs Build status updates of commit _[77a8043](https://github.com/brittmsantos/bingmaps-docs/commits/77a8043783f8bb6b3003eaa0de201bb5c862b3fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/v8-web-control/modules/directions-module/routeoptimization-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/directions-module/routeoptimization-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/directions-module/routeoptimization-enumeration?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/geoxml-module/kmlscreenoverlayoptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/geoxml-module/kmlscreenoverlayoptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/geoxml-module/kmlscreenoverlayoptions-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/heat-map-module/heatmaplayer-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/heat-map-module/heatmaplayer-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/heat-map-module/heatmaplayer-class?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/heat-map-module/heatmaplayeroptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/heat-map-module/heatmaplayeroptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/heat-map-module/heatmaplayeroptions-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/heat-map-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/heat-map-module/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/heat-map-module/index?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/index?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/address-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/address-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/address-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/geocodelocation-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/geocodelocation-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/geocodelocation-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/geocoderequestoptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/geocoderequestoptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/geocoderequestoptions-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/geocoderesult-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/geocoderesult-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/geocoderesult-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/index?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/matchcode-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/matchcode-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/matchcode-enumeration?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/matchconfidence-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/matchconfidence-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/matchconfidence-enumeration?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/placeresult-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/placeresult-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/placeresult-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/reversegeocoderequestoptions-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/reversegeocoderequestoptions-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/reversegeocoderequestoptions-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/search-module/searchmanager-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/search-module/searchmanager-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/search-module/searchmanager-class?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/copyright-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/copyright-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/copyright-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/copyrightsource-object.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/copyrightsource-object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/copyrightsource-object?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/filter-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/filter-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/filter-class?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/filtercompareoperator-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spatial-data-service-module/filtercompareoperator-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/modules/spatial-data-service-module/filtercompareoperator-enumeration?branch=pr-en-us-234) |
[BingMaps/v8-web-control/modules/spatial-data-service-module/filtergroup-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/modules/spa [...]

2022-06-08 18:03 UTC, stevemunk commented
@brittmsantos Thank you! Merging....

2022-06-08 18:03 UTC, merged