Validation: Added Missing Descriptions
MicrosoftDocs/bingmaps-docs pull request #240
Opened 2022-05-26 19:46 UTC by dereklh7

Added missing metadata descriptions.

2022-05-26 19:49 UTC, opbld32 commented
Docs Build status updates of commit _[6da2bb6](https://github.com/dereklh7/bingmaps-docs/commits/6da2bb607e1ba868bb34b4b25ed61a64cd4de441)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/sdk-native/map-control-concepts/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/index?branch=pr-en-us-240) | [Details](#user-content-7929ac75142175e901d140663352047c-7f12c9de)
[BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-styles-sheets?branch=pr-en-us-240) | [Details](#user-content-4a0c71342cd50a2764ffbc6fad92774e-7f12c9de)
[BingMaps/sdk-native/map-control-concepts/map-icons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-icons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/tile-layers.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/tile-layers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/tile-layers?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/index?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarning-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarning-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarning-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocation-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocation-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocation-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationaddress-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationaddress-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationaddress-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinder-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinder-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinder-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-servi [...]

2022-05-26 20:20 UTC, opbld33 commented
Docs Build status updates of commit _[9f76995](https://github.com/dereklh7/bingmaps-docs/commits/9f76995d5d1a1f1cd6de0b54347a990bf1cdb6cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/sdk-native/map-control-concepts/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/index?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-icons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-icons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-styles-sheets?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/tile-layers.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/tile-layers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/tile-layers?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/index?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarning-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarning-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarning-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocation-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocation-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocation-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationaddress-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationaddress-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationaddress-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinder-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinder-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinder-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ [...]

2022-05-26 20:44 UTC, opbld30 commented
Docs Build status updates of commit _[6c5b129](https://github.com/dereklh7/bingmaps-docs/commits/6c5b129f3dd806b8f73e294708cfe8c38a5940dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/sdk-native/map-control-concepts/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/index?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-icons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-icons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-styles-sheets?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/tile-layers.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/tile-layers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/tile-layers?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/index?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarning-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarning-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarning-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocation-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocation-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocation-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationaddress-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationaddress-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationaddress-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinder-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinder-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinder-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ [...]

2022-05-26 20:46 UTC, dereklh7 commented
@stevemunk @JuanPapas 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-06 17:33 UTC, opbld33 commented
Docs Build status updates of commit _[e2be119](https://github.com/dereklh7/bingmaps-docs/commits/e2be11951b347b416ccc7475efa5bd52434701ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-styles-sheets?branch=pr-en-us-240) | [Details](#user-content-4a0c71342cd50a2764ffbc6fad92774e-8a9b3582)
[BingMaps/sdk-native/map-control-concepts/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/index?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-icons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-icons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/tile-layers.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/tile-layers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/tile-layers?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/index?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarning-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarning-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarning-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocation-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocation-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocation-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationaddress-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationaddress-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationaddress-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinder-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinder-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinder-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration?branch=pr-en [...]

2022-06-06 17:36 UTC, opbld32 commented
Docs Build status updates of commit _[ddfe7ae](https://github.com/dereklh7/bingmaps-docs/commits/ddfe7aea8377f97c30011f01a36ea4869cf799c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/sdk-native/map-control-concepts/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/index?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-icons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-icons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-styles-sheets?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/tile-layers.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/tile-layers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/tile-layers?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/android/onmaproutefinderresultlistener-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/index?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/ios/maproutingcompletionblock-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarning-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarning-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarning-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarningkind-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maneuverwarningseverity-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocation-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocation-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocation-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationaddress-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationaddress-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationaddress-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinder-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinder-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinder-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ [...]

2022-06-06 17:36 UTC, dereklh7 commented
@stevemunk @JuanPapas

I've resolved all merge conflicts for this PR. Please let me know if there are any other issues preventing approval and merge for this PR. Thanks!

2022-06-09 17:37 UTC, stevemunk commented
@dereklh7 It looks like there are still conflicts.

2022-06-09 19:43 UTC, opbld33 commented
Docs Build status updates of commit _[3d4b479](https://github.com/dereklh7/bingmaps-docs/commits/3d4b4790c7451abfd3a466bb6ceccea045f9c46b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/sdk-native/map-control-concepts/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/index?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-icons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-icons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-styles-sheets?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/tile-layers.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/tile-layers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/tile-layers?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/index?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocation-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocation-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocation-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationaddress-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationaddress-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationaddress-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinder-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinder-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinder-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationmatchcode-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationmatchcode-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationmatchcode-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationoptions-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationoptions-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationoptions-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationpoint-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationpoint-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationpoint-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationpointcalculationmethod-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationpointcalculationmethod-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationpointcalculationmethod-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationpointusagetype-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationpointusagetype-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationpointusagetype-enumeration?branch=pr-en-us-240) |

For more details, please refer to the [build report](https://buildapi.docs.micr [...]

2022-06-09 19:45 UTC, dereklh7 commented
@stevemunk I've resolved all merge conflicts. Please let me know if there are any remaining issues on this PR preventing approval and merge. Thank you and have a great day!

2022-06-09 22:44 UTC, stevemunk requested changes

2022-06-09 22:44 UTC, stevemunk commented on BingMaps/sdk-native/map-control-concepts/map-icons.md
> +description: Describes icons's utility, outlines how to display icons on the map, and provides additional references.
```suggestion
description: Describes Icons, the primary way to add a graphical image and text at a location within the map using the Bing Maps native controls, with a link to examples and additional information.

  utility, outlines how to display icons on the map, and provides additional references.
```

2022-06-09 22:44 UTC, stevemunk commented on BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md
> +description: Describes polylines and polygons and provides additional resources and examples to provide guidance for drawing with polylines and polygons.
```suggestion
description: Describes polylines and polygons with a link to examples and additional information.
```

2022-06-09 22:44 UTC, stevemunk commented on BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md
> +description: Describes map style sheets and the MapStyleSheet static methods and provides information on default and custom map style sheets.
```suggestion
description: Describes map style sheets, which represent a set of rules that define the style of the map in a map view, including a table listing the default styles such as Aerial, RoadDark and RoadHighContrastDark and links to articles describing how to create custom map styles.

```

2022-06-09 22:44 UTC, stevemunk commented on BingMaps/sdk-native/map-services-api/index.md
> +description: Provides a reference of MapServices API through tables that outline details for various classes, enumerations, and interfaces.
```suggestion
description: The overview page for the MapServices API Reference section contains tables containing descriptions and links to more information for each of the MapServices classes, Enumerations and interfaces.
```

2022-06-09 22:44 UTC, stevemunk commented on BingMaps/sdk-native/map-services-api/maplocationaddress-class.md
> +description: Describes the MapLocationAddress class for Android and iOS and provides the class's properties and additional references.
```suggestion
description: Describes the MapLocationAddress class for Android and iOS with descriptions for each of its properties.
```

2022-06-09 23:03 UTC, opbld30 commented
Docs Build status updates of commit _[c2e303b](https://github.com/dereklh7/bingmaps-docs/commits/c2e303b592ac6c4e3bf9300068b284be28c6c962)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/sdk-native/map-control-concepts/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/index?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-icons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-icons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-polylines-and-polygons?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-scenes-and-cameras?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/map-styles-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/map-styles-sheets?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/tile-layers.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/tile-layers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/tile-layers?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-control-concepts/user-interface-gestures-and-controls?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/android/onmaplocationfinderresultlistener-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/index?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/ios/maplocationfinderresulthandler-interface?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocation-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocation-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocation-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationaddress-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationaddress-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationaddress-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationentitytypes-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinder-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinder-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinder-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinderresult-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationfinderstatus-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationmatchcode-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationmatchcode-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationmatchcode-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationoptions-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationoptions-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationoptions-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationpoint-class.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationpoint-class.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationpoint-class?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationpointcalculationmethod-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationpointcalculationmethod-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationpointcalculationmethod-enumeration?branch=pr-en-us-240) |
[BingMaps/sdk-native/map-services-api/maplocationpointusagetype-enumeration.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/map-services-api/maplocationpointusagetype-enumeration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/map-services-api/maplocationpointusagetype-enumeration?branch=pr-en-us-240) |

For more details, please refer to the [build report](https://buildapi.docs.micr [...]

2022-06-09 23:07 UTC, dereklh7 commented
@stevemunk I've implemented the requested fixes. Please let me know if there are any remaining issues that are preventing approval and merge for this PR. Thanks for looking at all these PRs, Steve! Your work is much appreciated!

2022-06-10 17:04 UTC, merged