Validation: description-missing fixes.
MicrosoftDocs/bingmaps-docs pull request #242
Opened 2022-05-26 23:18 UTC by brittmsantos

2022-05-26 23:20 UTC, opbld32 commented
Docs Build status updates of commit _[e26ff91](https://github.com/brittmsantos/bingmaps-docs/commits/e26ff91af216c35bf42649265a5da36985cc1658)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/v8-web-control/map-control-concepts/rest-services-examples/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/rest-services-examples/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/rest-services-examples/index?branch=pr-en-us-242) | [Details](#user-content-8562af0c218aba5b1ba57005b95b11c9-01dfd8f7)
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/basic-polyline-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/basic-polyline-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/basic-polyline-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/index?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygon-events.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygon-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygon-events?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygons-with-holes-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygons-with-holes-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygons-with-holes-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polyline-events.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polyline-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polyline-events?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/creating-custom-modules.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/creating-custom-modules.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/creating-custom-modules?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/implementing-modules.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/implementing-modules.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/implementing-modules?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/index?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/module-loading-methods.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/module-loading-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/module-loading-methods?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/point-compression-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/point-compression-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/point-compression-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/anchoring-pushpins.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/anchoring-pushpins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/anchoring-pushpins?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/changing-the-color-of-the-default-pushpin.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/changing-the-color-of-the-default-pushpin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/changing-the-color-of-the-default-pushpin?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-base64-image-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-base64-image-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-base64-image-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-canvas-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-canvas-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-canvas-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-image-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-image-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-image-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-inline-svg-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-inline-svg-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-inline-svg-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-svg-file-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-svg-file-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-svg-file-pushpin-example?branch=pr-en-u [...]

2022-05-26 23:24 UTC, opbld32 commented
Docs Build status updates of commit _[8d0f885](https://github.com/brittmsantos/bingmaps-docs/commits/8d0f885ae131e490060702b1ea851e5cd567af3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/basic-polyline-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/basic-polyline-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/basic-polyline-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/index?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygon-events.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygon-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygon-events?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygons-with-holes-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygons-with-holes-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygons-with-holes-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polyline-events.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polyline-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polyline-events?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/creating-custom-modules.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/creating-custom-modules.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/creating-custom-modules?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/implementing-modules.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/implementing-modules.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/implementing-modules?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/index?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/module-loading-methods.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/module-loading-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/module-loading-methods?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/point-compression-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/point-compression-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/point-compression-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/anchoring-pushpins.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/anchoring-pushpins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/anchoring-pushpins?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/changing-the-color-of-the-default-pushpin.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/changing-the-color-of-the-default-pushpin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/changing-the-color-of-the-default-pushpin?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-base64-image-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-base64-image-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-base64-image-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-canvas-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-canvas-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-canvas-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-image-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-image-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-image-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-inline-svg-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-inline-svg-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-inline-svg-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-svg-file-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-svg-file-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-svg-file-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/default-pushpin-with-text-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/default-pushpin-with-text-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/default-pushpin-with-text-example?branch=pr-en-us-242)  [...]

2022-05-27 20:02 UTC, opbld33 commented
Docs Build status updates of commit _[0a79a6d](https://github.com/brittmsantos/bingmaps-docs/commits/0a79a6d0bcebec1f1fb5913631ea2f594db0e6bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/basic-polyline-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/basic-polyline-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/basic-polyline-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/index?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygon-events.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygon-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygon-events?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygons-with-holes-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygons-with-holes-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygons-with-holes-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polyline-events.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polyline-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polyline-events?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/creating-custom-modules.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/creating-custom-modules.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/creating-custom-modules?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/implementing-modules.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/implementing-modules.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/implementing-modules?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/index?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/module-loading-methods.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/module-loading-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/module-loading-methods?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/point-compression-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/point-compression-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/point-compression-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/anchoring-pushpins.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/anchoring-pushpins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/anchoring-pushpins?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/changing-the-color-of-the-default-pushpin.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/changing-the-color-of-the-default-pushpin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/changing-the-color-of-the-default-pushpin?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-base64-image-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-base64-image-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-base64-image-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-canvas-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-canvas-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-canvas-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-image-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-image-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-image-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-inline-svg-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-inline-svg-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-inline-svg-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-svg-file-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-svg-file-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-svg-file-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/default-pushpin-with-text-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/default-pushpin-with-text-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/default-pushpin-with-text-example?branch=pr-en-us-242)  [...]

2022-05-27 20:12 UTC, brittmsantos commented
@stevemunk @rbrundritt

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-10 21:55 UTC, stevemunk requested changes

2022-06-10 21:55 UTC, stevemunk commented on BingMaps/v8-web-control/map-control-concepts/pushpins/default-pushpin-with-text-example.md
> +description: Provides a code example that shows how to change the default pushpin on the map to have a number and a text label.
```suggestion
description: Example code demonstrating how to create a pushpin at the center of the map and set values for the text, title and subTitle properties.
```

2022-06-10 21:55 UTC, stevemunk commented on BingMaps/v8-web-control/map-control-concepts/pushpins/dynamically-create-svg-pushpin-example.md
> +description: Provides a code example that shows how to dynamically create SVG circles for pushpin icons using a custom function.
```suggestion
description: Example code demonstrating how to dynamically create SVG circles for pushpin icons using a custom function.
```

2022-06-10 21:55 UTC, stevemunk commented on BingMaps/v8-web-control/map-control-concepts/pushpins/font-based-pushpins.md
> +description: Provides how to use a custom font from the Font Awesome library to create custom pushpin icons for usage on a map.
```suggestion
description: Example code demonstrating how to use a custom font to create a pushpin icon using an off-screen canvas to measure the text and create an image from the font. Fonts are created using the Font Awesome library.
```

2022-06-10 21:55 UTC, stevemunk commented on BingMaps/v8-web-control/map-control-concepts/pushpins/image-and-canvas-pushpin-example.md
> +description: Provides a code example that shows how to create custom colored pushpins that use an image as a template.
```suggestion
description: Example code demonstrating how to create custom colored pushpins that use an image as a template.
```

2022-06-10 21:55 UTC, stevemunk commented on BingMaps/v8-web-control/map-control-concepts/pushpins/index.md
> +description: Describes pushpins, which act as graphical image and text representations of locations on maps, and provides links to code examples.
```suggestion
description: The overview page for the Pushpins section contains a description and links to examples and related topics.
```

2022-06-10 21:55 UTC, stevemunk commented on BingMaps/v8-web-control/map-control-concepts/rest-services-examples/index.md
> +description: Describes the functionalities of the Bing Maps REST API services, and provides a list of Bing Maps REST services code examples.
```suggestion
description: Describes the Bing Maps REST services, accessed using GET requests with JSONP, with example code demonstrating how to implement using standard JavaScript, jQuery, AngularJS.
```

2022-06-10 21:55 UTC, stevemunk commented on BingMaps/v8-web-control/map-control-concepts/search-module-examples/index.md
> +description: Describes the Search module and provides a list of code examples and related topic articles to the Search module.
```suggestion
description: Describes the Search module and provides links to code examples and related topic. 
```

2022-06-10 21:55 UTC, stevemunk commented on BingMaps/v8-web-control/map-control-concepts/search-module-examples/user-input-geocode-example.md
> +description: Provides a code example that displays a search field and button which allows a user to perform a search for a location and then lists the results.
```suggestion
description: Example code demonstrating how to display a search field and button on a map. When the button is selected the search query is geocoded and the results are displayed on the map and a list of the result names are shown beside the map.
```

2022-06-13 16:22 UTC, opbld32 commented
Docs Build status updates of commit _[01cc073](https://github.com/brittmsantos/bingmaps-docs/commits/01cc0730874c948f7ec562d3a065a8e707700da6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/basic-polyline-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/basic-polyline-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/basic-polyline-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/index?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygon-events.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygon-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygon-events?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygons-with-holes-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygons-with-holes-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polygons-with-holes-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polyline-events.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polyline-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/map-shapes-polylines-and-polygons/polyline-events?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/creating-custom-modules.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/creating-custom-modules.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/creating-custom-modules?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/implementing-modules.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/implementing-modules.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/implementing-modules?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/index?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/modular-framework/module-loading-methods.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/modular-framework/module-loading-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/modular-framework/module-loading-methods?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/point-compression-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/point-compression-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/point-compression-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/anchoring-pushpins.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/anchoring-pushpins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/anchoring-pushpins?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/changing-the-color-of-the-default-pushpin.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/changing-the-color-of-the-default-pushpin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/changing-the-color-of-the-default-pushpin?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-base64-image-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-base64-image-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-base64-image-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-canvas-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-canvas-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-canvas-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-image-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-image-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-image-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-inline-svg-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-inline-svg-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-inline-svg-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/custom-svg-file-pushpin-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-svg-file-pushpin-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/custom-svg-file-pushpin-example?branch=pr-en-us-242) |
[BingMaps/v8-web-control/map-control-concepts/pushpins/default-pushpin-with-text-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/map-control-concepts/pushpins/default-pushpin-with-text-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/map-control-concepts/pushpins/default-pushpin-with-text-example?branch=pr-en-us-242)  [...]

2022-06-13 16:24 UTC, brittmsantos commented
@stevemunk 

I've implemented the requested changes. Please let me know if there are any other issues preventing approval and merge. Thank you, and have a great day!

2022-06-15 21:20 UTC, merged