Validation: Added Missing Descriptions
MicrosoftDocs/bingmaps-docs pull request #243
Opened 2022-05-27 18:16 UTC by dereklh7

Added missing metadata description, fixed broken links, and added column headers.

2022-05-27 18:18 UTC, opbld30 commented
Docs Build status updates of commit _[099a7ec](https://github.com/dereklh7/bingmaps-docs/commits/099a7ec3cfb690134b05622f5bc95bb1e5aafb98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-data-schema-and-sample-input.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-data-schema-and-sample-input.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-data-schema-and-sample-input?branch=pr-en-us-243) | [Details](#user-content-e6de5879363f8c3e012dc324d8175de9-2f1303ee)
[BingMaps/spatial-data-services/geodata-api.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geodata-api.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geodata-api?branch=pr-en-us-243) | [Details](#user-content-748f202a261f6ce9c1c2fde5028f61ed-2f1303ee)
[BingMaps/spatial-data-services/getting-started-with-the-spatial-data-services.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/getting-started-with-the-spatial-data-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/getting-started-with-the-spatial-data-services?branch=pr-en-us-243) | [Details](#user-content-a71b7d474fa6c2547a00b8ebd8726884-2f1303ee)
[BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-dataflow-sample-code-vb.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-dataflow-sample-code-vb.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-dataflow-sample-code-vb?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/publish-staged-data-source.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/publish-staged-data-source.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/publish-staged-data-source?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/make-public-data-source.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/make-public-data-source.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/make-public-data-source?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/rollback-data-source-dataflow.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/rollback-data-source-dataflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/rollback-data-source-dataflow?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/developer-resources.md](https://github.com/dereklh7/bingmaps-docs/blob/Description-5-27/BingMaps/spatial-data-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/developer-resources?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-and-data-source-limits.md](https://github.com/dereklh7/bingmaps-docs/blob/Description-5-27/BingMaps/spatial-data-services/geocode-and-data-source-limits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-and-data-source-limits?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/create-a-geocode-job-and-upload-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/create-a-geocode-job-and-upload-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/create-a-geocode-job-and-upload-data?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/download-geocode-job-results.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/download-geocode-job-results.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/download-geocode-job-results?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-1-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-1-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-1-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-2-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-2-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-2-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-response-description?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-code.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-code.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-code?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-1-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-1-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-1-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-2-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-2-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-2-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-walkthrough.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/mai [...]

2022-05-27 18:26 UTC, brittmsantos commented on BingMaps/spatial-data-services/geocode-dataflow-api/get-status-of-a-geocode-job.md
> +description: "Describes how to get the status of a geocode job b and provides supported HTTP methods, the URL template, template parameters, and examples."
"geocode job b"--seems like the b at the end is unnecessary?

2022-05-27 18:26 UTC, opbld33 commented
Docs Build status updates of commit _[9f94fc2](https://github.com/dereklh7/bingmaps-docs/commits/9f94fc29fdcb3661ed64dcb1fed7038384d6687f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-data-schema-and-sample-input.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-data-schema-and-sample-input.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-data-schema-and-sample-input?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-dataflow-sample-code-vb.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-dataflow-sample-code-vb.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-dataflow-sample-code-vb?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/publish-staged-data-source.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/publish-staged-data-source.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/publish-staged-data-source?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/make-public-data-source.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/make-public-data-source.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/make-public-data-source?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/rollback-data-source-dataflow.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/rollback-data-source-dataflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/rollback-data-source-dataflow?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/developer-resources.md](https://github.com/dereklh7/bingmaps-docs/blob/Description-5-27/BingMaps/spatial-data-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/developer-resources?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-and-data-source-limits.md](https://github.com/dereklh7/bingmaps-docs/blob/Description-5-27/BingMaps/spatial-data-services/geocode-and-data-source-limits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-and-data-source-limits?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/create-a-geocode-job-and-upload-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/create-a-geocode-job-and-upload-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/create-a-geocode-job-and-upload-data?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/download-geocode-job-results.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/download-geocode-job-results.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/download-geocode-job-results?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-1-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-1-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-1-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-2-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-2-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-2-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-response-description?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-code.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-code.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-code?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-1-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-1-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-1-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-2-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-2-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-2-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-walkthrough.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-walkthrough.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-walkthrough?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/get-status-of-a-geocode-job.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/get-status-of-a-geocode-job.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/get-status-of-a-geocode-job?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/index.md) | :whit [...]

2022-06-06 17:37 UTC, dereklh7 commented
@stevemunk @rbrundritt

Checking in on the status of this PR to see if there are any changes that need to be implemented for this PR to be approved and merged. Thanks!

2022-06-06 18:14 UTC, stevemunk commented
@dereklh7 Looking now...

2022-06-07 22:54 UTC, stevemunk requested changes

2022-06-07 22:54 UTC, stevemunk commented on BingMaps/spatial-data-services/geocode-dataflow-api/index.md
> +description: "Describes the Geocode Dataflow API and provides a table that outlines a description for various resources relating to the API."
```suggestion
description: "The overview page for the Geocode Dataflow API, which uses REST URLs to geocode and reverse-geocode large sets of spatial data, with information on what you need to do in order to use these API along with links to articles that describe the data schema, how to create and check on jobs, download results, sample input/output files, sample code and a walkthrough."
```

2022-06-07 22:54 UTC, stevemunk commented on BingMaps/spatial-data-services/index.md
> +description: "Describes Bing Spatial Data Services and provides a table that outlines a description for various resources relating to Bing Spatial Data Services."
```suggestion
description: "The overview page for the Spatial Data Services section, which uses REST URLS to geocode, store and query spatial data. Describes what you can do with these API and contains a list of links to topics in this section with descriptions for each."
```

2022-06-07 22:54 UTC, stevemunk commented on BingMaps/spatial-data-services/public-data-sources/fourthcoffeesample.md
> +description: "Describes the FourthCoffeeSample data source and provides a table that outlines the data type and example value for various properties."
```suggestion
description: "Describes the FourthCoffeeSample data source, a sample data source used when learning how to query and get data source information using the Bing Spatial Data Services, with a table that outlines the data type and example value for each of its properties."
```

2022-06-07 22:54 UTC, stevemunk commented on BingMaps/spatial-data-services/public-data-sources/index.md
> +description: "Describes Bing Spatial Data Services' public data sources and provides a table that outlines a description for various data sources."
```suggestion
description: "The overview page for the Public Data Sources section, with a list of links to each data source available and a description for each."
```

2022-06-07 22:54 UTC, stevemunk commented on BingMaps/spatial-data-services/query-api/index.md
> +description: "Describes the Query API and provides a table that outlines a description for various resources related to the Query API."
```suggestion
description: "The overview page for the Query API section, with links to each of the articles in this section and a description for each."
```

2022-06-07 22:54 UTC, stevemunk commented on BingMaps/spatial-data-services/query-api/query-api-sample-code-csharp.md
> +description: "Provides C# sample code for the Query API. This sample code provides an example of how to query a data source using the Query API."
```suggestion
description: "The Query API Sample Code, written in C#, provides examples of how to query a data source using the Query API."
```

2022-06-07 23:13 UTC, opbld33 commented
Docs Build status updates of commit _[eabafd3](https://github.com/dereklh7/bingmaps-docs/commits/eabafd31c8e444d92181ee27ec6f8a52f1a0367e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-data-schema-and-sample-input.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-data-schema-and-sample-input.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-data-schema-and-sample-input?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-dataflow-sample-code-vb.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-dataflow-sample-code-vb.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-dataflow-sample-code-vb?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/publish-staged-data-source.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/publish-staged-data-source.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/publish-staged-data-source?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/make-public-data-source.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/make-public-data-source.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/make-public-data-source?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/rollback-data-source-dataflow.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/rollback-data-source-dataflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/rollback-data-source-dataflow?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/developer-resources.md](https://github.com/dereklh7/bingmaps-docs/blob/Description-5-27/BingMaps/spatial-data-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/developer-resources?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-and-data-source-limits.md](https://github.com/dereklh7/bingmaps-docs/blob/Description-5-27/BingMaps/spatial-data-services/geocode-and-data-source-limits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-and-data-source-limits?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/create-a-geocode-job-and-upload-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/create-a-geocode-job-and-upload-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/create-a-geocode-job-and-upload-data?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/download-geocode-job-results.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/download-geocode-job-results.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/download-geocode-job-results?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-1-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-1-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-1-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-2-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-2-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-2-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-response-description?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-code.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-code.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-code?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-1-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-1-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-1-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-2-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-2-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-2-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-walkthrough.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-walkthrough.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-walkthrough?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/get-status-of-a-geocode-job.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/get-status-of-a-geocode-job.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/get-status-of-a-geocode-job?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/index.md) | :whit [...]

2022-06-07 23:17 UTC, dereklh7 commented
@stevemunk I've implemented the requested changes. Please let me know if there are any other additional issues preventing approval and merge for this PR. Thanks! Hope you have a great rest of your day!

2022-06-08 01:31 UTC, stevemunk commented
@dereklh7 can you please remove the file: BingMaps/spatial-data-services/public-data-sources/navteqeu.md? It is outdated. I removed it via a different PR, which created a merge conflict that cannot be resolved using the github website, thought it might just be easier that fixing the merge conflict using the console, not something I've needed to do.

2022-06-08 14:59 UTC, opbld30 commented
Docs Build status updates of commit _[dcac0b5](https://github.com/dereklh7/bingmaps-docs/commits/dcac0b56f41cfa82adc9232b397526ff193bd182)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/spatial-data-services/public-data-sources/navteqeu.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/public-data-sources/navteqeu.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/public-data-sources/navteqeu?branch=pr-en-us-243) | [Details](#user-content-da8d4dc239fa1e1935676cf71e9c29a7-adda04fa)
[BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-data-schema-and-sample-input.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-data-schema-and-sample-input.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-data-schema-and-sample-input?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-dataflow-sample-code-vb.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-dataflow-sample-code-vb.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/load-data-source-dataflow-sample-code-vb?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/publish-staged-data-source.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/publish-staged-data-source.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/load-data-source-dataflow/publish-staged-data-source?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/make-public-data-source.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/make-public-data-source.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/make-public-data-source?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/data-source-management-api/rollback-data-source-dataflow.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/data-source-management-api/rollback-data-source-dataflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/rollback-data-source-dataflow?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/developer-resources.md](https://github.com/dereklh7/bingmaps-docs/blob/Description-5-27/BingMaps/spatial-data-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/developer-resources?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-and-data-source-limits.md](https://github.com/dereklh7/bingmaps-docs/blob/Description-5-27/BingMaps/spatial-data-services/geocode-and-data-source-limits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-and-data-source-limits?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/create-a-geocode-job-and-upload-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/create-a-geocode-job-and-upload-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/create-a-geocode-job-and-upload-data?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/download-geocode-job-results.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/download-geocode-job-results.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/download-geocode-job-results?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-1-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-1-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-1-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-2-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-2-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-data-schema-version-2-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-response-description?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-code.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-code.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-code?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-1-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-1-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-1-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-2-0.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-2-0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-sample-input-and-output-data-version-2-0?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-walkthrough.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-walkthrough.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/geocode-dataflow-api/geocode-dataflow-walkthrough?branch=pr-en-us-243) |
[BingMaps/spatial-data-services/geocode-dataflow-api/get-status-of-a-geocode-job.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/geocode-dataflow-api [...]

2022-06-08 15:03 UTC, dereklh7 commented
@stevemunk In an attempt to resolve this merge conflict in VS Code, I ended up reverting all changes originally made to navteqeu.md - that file now appears unedited from before this PR. Does that work? If not, please let me know.

2022-06-08 16:41 UTC, merged

2022-06-13 17:49 UTC, stevemunk commented
@dereklh7 Since that file is no longer in main, it seems that if you merged/sync'd with main, it should remove it from your working branch as well. It shouldn't be showing up at all as a part of this PR, I'm worried that if I merge, it will create this file again in main.