[Bulk] Validation Fixes
MicrosoftDocs/bingmaps-docs pull request #248
Opened 2022-05-31 04:37 UTC by AqMoh

This PR fixes 40 issues.

2022-05-31 04:39 UTC, opbld30 commented
Docs Build status updates of commit _[8bf8dee](https://github.com/AqMoh/bingmaps-docs/commits/8bf8dee0484a1b42c9aebae2f741f179c8cda86b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-248) | [Details](#user-content-3b540ec6b732e096901247770e720565-40e95851)
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-248) | [Details](#user-content-63e27e0ed98097318737ba867d1c03ae-40e95851)
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-248) | [Details](#user-content-e196b363c395ddb8b78e0a070e8de9f3-40e95851)
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-248) | [Details](#user-content-99093358059c624fd9689ae552849ec4-40e95851)
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-248) | [Details](#user-content-8c9d80b823cc46c0f3cc739693a854e4-40e95851)
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-248) | [Details](#user-content-c1bdc3455bd82855564cf218ed3bc3c9-40e95851)
[BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps?branch=pr-en-us-248) | [Details](#user-content-fd4b0a0c2b617c19dce7c0966d50c1a5-40e95851)
[BingMaps/spatial-data-services/query-api/query-by-area.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-area.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-area?branch=pr-en-us-248) | [Details](#user-content-51d3eb6f9fb3c0e24f269fe19c8a86ff-40e95851)
[BingMaps/spatial-data-services/query-api/query-by-id.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-id.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-id?branch=pr-en-us-248) | [Details](#user-content-98e8b23c2b84ef255f3c5eb36aeaa81d-40e95851)
[BingMaps/spatial-data-services/query-api/query-near-route.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-near-route.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-near-route?branch=pr-en-us-248) | [Details](#user-content-d5160ffd3ce9bc54d4e73c6301acfd65-40e95851)
[BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-property.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-property.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-property?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-response-description?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/release-history.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/release-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/release-history?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/status-codes-and-error-handling.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/status-codes-and-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/status-codes-and-error-handling?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/code-optimizations-in-v8.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/code-optimizations-in-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/code-optimizations-in-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/map-keyboard-shortcuts?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/vector-map-labels.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/vector-map-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/vector-map-labels?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.mic [...]

2022-05-31 04:52 UTC, opbld30 commented
Docs Build status updates of commit _[ef910e9](https://github.com/AqMoh/bingmaps-docs/commits/ef910e9b845a4734d04aa0a523b6c6330b0ea677)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-248) | [Details](#user-content-3b540ec6b732e096901247770e720565-eeb4840b)
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-248) | [Details](#user-content-63e27e0ed98097318737ba867d1c03ae-eeb4840b)
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-248) | [Details](#user-content-e196b363c395ddb8b78e0a070e8de9f3-eeb4840b)
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-248) | [Details](#user-content-99093358059c624fd9689ae552849ec4-eeb4840b)
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-248) | [Details](#user-content-8c9d80b823cc46c0f3cc739693a854e4-eeb4840b)
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-248) | [Details](#user-content-c1bdc3455bd82855564cf218ed3bc3c9-eeb4840b)
[BingMaps/spatial-data-services/query-api/query-by-id.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-id.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-id?branch=pr-en-us-248) | [Details](#user-content-98e8b23c2b84ef255f3c5eb36aeaa81d-eeb4840b)
[BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-area.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-area.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-area?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-property.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-property.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-property?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-near-route.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-near-route.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-near-route?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-response-description?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/release-history.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/release-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/release-history?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/status-codes-and-error-handling.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/status-codes-and-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/status-codes-and-error-handling?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/code-optimizations-in-v8.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/code-optimizations-in-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/code-optimizations-in-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/map-keyboard-shortcuts?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/vector-map-labels.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/vector-map-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/vector-map-labels?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/map-c [...]

2022-05-31 05:13 UTC, opbld31 commented
Docs Build status updates of commit _[a31b68f](https://github.com/AqMoh/bingmaps-docs/commits/a31b68f2d248993ee75159511dbc10d090ab2053)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/spatial-data-services/query-api/query-by-id.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-id.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-id?branch=pr-en-us-248) | [Details](#user-content-98e8b23c2b84ef255f3c5eb36aeaa81d-98ff037f)
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-248) | [Details](#user-content-63e27e0ed98097318737ba867d1c03ae-98ff037f)
[BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-area.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-area.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-area?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-property.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-property.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-property?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-near-route.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-near-route.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-near-route?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-response-description?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/release-history.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/release-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/release-history?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/status-codes-and-error-handling.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/status-codes-and-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/status-codes-and-error-handling?branch=pr-en-us-248) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/code-optimizations-in-v8.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/code-optimizations-in-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/code-optimizations-in-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/map-keyboard-shortcuts?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/vector-map-labels.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/vector-map-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/vector-map-labels?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-a [...]

2022-05-31 15:40 UTC, opbld32 commented
Docs Build status updates of commit _[2de987d](https://github.com/AqMoh/bingmaps-docs/commits/2de987d82edf048ae3db7e1cfb534654e7e8fea8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-area.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-area.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-area?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-id.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-id.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-id?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-property.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-property.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-property?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-near-route.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-near-route.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-near-route?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-response-description?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/release-history.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/release-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/release-history?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/status-codes-and-error-handling.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/status-codes-and-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/status-codes-and-error-handling?branch=pr-en-us-248) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/code-optimizations-in-v8.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/code-optimizations-in-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/code-optimizations-in-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/map-keyboard-shortcuts?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/vector-map-labels.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/vector-map-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/vector-map-labels?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hostin [...]

2022-05-31 19:13 UTC, jmart1428 commented on BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md
> +To safeelist these domains in a native Windows 10, open the **config.xml** file in your Cordova project and near top of the file you should see "&lt;access origin="\*" /&gt;" after this line add the
remove extra 'e' in 'safeelist'

2022-05-31 19:15 UTC, jmart1428 commented on BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md
> +If you project doesn’t work after safelisting these URLs ensure that the version of Windows that your app targets is 10. There is a preference property in the **config.xml** file that specifies the t
Just happened to notice typo. "If you project" should be "If your project". Might as well fix if you're already going back into this file.

2022-05-31 19:17 UTC, jmart1428 commented on BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches.md
> +description: "This article describes the two branches of the Bing Maps V8 SDK that can be accessed, as well as a URL can be used to load the experimental branch."
"as well as a URL **that** can be used..."

2022-06-01 00:33 UTC, opbld33 commented
Docs Build status updates of commit _[0587c0e](https://github.com/AqMoh/bingmaps-docs/commits/0587c0e5f29a965bcd0160ab1f8019f46d7b3e23)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-area.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-area.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-area?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-id.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-id.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-id?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-property.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-property.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-property?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-near-route.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-near-route.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-near-route?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-response-description?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/release-history.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/release-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/release-history?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/status-codes-and-error-handling.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/status-codes-and-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/status-codes-and-error-handling?branch=pr-en-us-248) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/code-optimizations-in-v8.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/code-optimizations-in-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/code-optimizations-in-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/map-keyboard-shortcuts?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/vector-map-labels.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/vector-map-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/vector-map-labels?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hostin [...]

2022-06-01 00:33 UTC, AqMoh commented
**Global effort to fix build validation errors**
@stevemunk 
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-11 00:57 UTC, opbld32 commented
Docs Build status updates of commit _[11be965](https://github.com/AqMoh/bingmaps-docs/commits/11be9655cf598d0f11810a25c5ff63843f1175aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-area.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-area.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-area?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-id.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-id.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-id?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-property.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-by-property.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-property?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-near-route.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-near-route.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-near-route?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/query-api/query-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-response-description?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/release-history.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/spatial-data-services/release-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/release-history?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/status-codes-and-error-handling.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/status-codes-and-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/status-codes-and-error-handling?branch=pr-en-us-248) |
[BingMaps/styling/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheets.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/code-optimizations-in-v8.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/code-optimizations-in-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/code-optimizations-in-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/cross-platform-bing-maps-v8-apps?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/map-keyboard-shortcuts?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/vector-map-labels.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/vector-map-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/vector-map-labels?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hostin [...]

2022-06-14 19:15 UTC, stevemunk requested changes

2022-06-14 19:15 UTC, stevemunk commented on BingMaps/v8-web-control/creating-and-hosting-map-controls/setting-map-control-parameters.md
> +description: "This article provides guidelines on how to add a parameter to the map control src URL and localizing the map. A list of parameter URLs with their descriptions are also provided."
```suggestion
description: "This article explains how to set map control parameters and includes descriptions for all available parameters, also describes how to localize the map control including overriding the detected settings using the setLang and setMkt parameters."
```

2022-06-16 19:14 UTC, stevemunk commented
@AqMoh Please let me know when you are finished making updates, thanks!

2022-06-20 18:14 UTC, opbld33 commented
Docs Build status updates of commit _[d6e40e6](https://github.com/AqMoh/bingmaps-docs/commits/d6e40e6900d46ca3af7f866411726a49510c2ea5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-078b62e5)

<a id="078b62e5"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206201814061824-248/BuildReport?accessString=35f3753ee07a99dd2df8d87e7a5028b333fb27b7b0e64d010cd399764a1bc597).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 18:15 UTC, opbld33 commented
Docs Build status updates of commit _[da4ba1b](https://github.com/AqMoh/bingmaps-docs/commits/da4ba1bdcd9b25e48ce8a05c7567e28134ed8ad0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3fd9ebdf)

<a id="3fd9ebdf"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206201814477357-248/BuildReport?accessString=33d90679645996d94ef094e28ce7811d7cb9b5b4fcd1902bded4d7d56d5138fd).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 18:16 UTC, opbld32 commented
Docs Build status updates of commit _[8de5e08](https://github.com/AqMoh/bingmaps-docs/commits/8de5e08cedad0033f5852d5be646ad6827ff085a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2489193b)

<a id="2489193b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206201814361840-248/BuildReport?accessString=e3e139633afd7f4497714397f80c90a11b2ae62a75644423ae39e895305f8dea).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 18:17 UTC, opbld31 commented
Docs Build status updates of commit _[98496e9](https://github.com/AqMoh/bingmaps-docs/commits/98496e9b8ccd9aace2d67a7035837cd4aab5eaf3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7b43c908)

<a id="7b43c908"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206201814149000-248/BuildReport?accessString=158567aa5509c2ea18092534f75c3c781a01a797f0a0b81eb320258dfe1400f3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 18:19 UTC, opbld33 commented
Docs Build status updates of commit _[ab63c45](https://github.com/AqMoh/bingmaps-docs/commits/ab63c45f0238a42b7f5d474d8654f086ecca7217)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-65a81202)

<a id="65a81202"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206201814242689-248/BuildReport?accessString=10da0d0c5f61d5791529d80f7a14d45630e5451265735fbc070237c6749bdbaf).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 18:19 UTC, opbld31 commented
Docs Build status updates of commit _[c4bf157](https://github.com/AqMoh/bingmaps-docs/commits/c4bf157c4d7d1f82861b4b98c37dd1395b6a810e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f34413a5)

<a id="f34413a5"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206201815264504-248/BuildReport?accessString=ae2441c2c39b2bad85497c4025b4b3a98d2fdbbb29328b0a6617b90a9cfbccf8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 18:20 UTC, opbld31 commented
Docs Build status updates of commit _[c09510d](https://github.com/AqMoh/bingmaps-docs/commits/c09510d05b5560f8e5d0305cdd50c3fddc2742cc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e51e5fa4)

<a id="e51e5fa4"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206201815180262-248/BuildReport?accessString=bbfc7b93d5e1844480707aeb4b36a13acf7ce2deb2c78d1778b56bf5f1641da1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 18:21 UTC, opbld33 commented
Docs Build status updates of commit _[a16137c](https://github.com/AqMoh/bingmaps-docs/commits/a16137ccf1fa39d73693e02bc56037de7a7a825d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-07c7fafb)

<a id="07c7fafb"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206201815120608-248/BuildReport?accessString=441c9d3b4b28e08a3843d329ca2f7ef3b8da3c59c472d4b3f2b1e476473bc74c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 18:21 UTC, opbld30 commented
Docs Build status updates of commit _[4c4946a](https://github.com/AqMoh/bingmaps-docs/commits/4c4946aee767dc7a7b4fcb4273b18446b1251f1c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f060f3af)

<a id="f060f3af"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206201815491904-248/BuildReport?accessString=86a62aa2b3a84b14cab45b2dc82599f9d12ff54343ed9bb56cecafcea934ed67).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 18:23 UTC, opbld33 commented
Docs Build status updates of commit _[3ec0145](https://github.com/AqMoh/bingmaps-docs/commits/3ec014510e4817b1cc1aa06a54c3a7b244fbe5f5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-779cf28d)

<a id="779cf28d"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206201815373727-248/BuildReport?accessString=77deca5d808f2a9dc0facc2aa636dd2db2ebaabe6313a64ee074ebef5aa78b2f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 18:50 UTC, opbld31 commented
Docs Build status updates of commit _[ecc5a72](https://github.com/AqMoh/bingmaps-docs/commits/ecc5a72440eda61617ab3928e5149b4668b3f7e2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-785fdf17)

<a id="785fdf17"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206201849330077-248/BuildReport?accessString=e5c155e616bd7765fbf38a5e8610d14a5d4325ee5da7a50932cad102824556ad).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 01:54 UTC, opbld32 commented
Docs Build status updates of commit _[8859ef7](https://github.com/AqMoh/bingmaps-docs/commits/8859ef766a9359c7b975fdb14b0eda5eee15448c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-def72259)

<a id="def72259"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206220153379777-248/BuildReport?accessString=58ae8b377cc2ad053a2645b31f3b8868dd7e32e524deffc071684282e8e22bf8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 01:57 UTC, opbld33 commented
Docs Build status updates of commit _[867b9d9](https://github.com/AqMoh/bingmaps-docs/commits/867b9d9bc1c49aca3db92a536fe26094e0d50a85)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/index?branch=pr-en-us-248) | [Details](#user-content-a0f52ab0dbab780b336385686b00d2d9-c407e15f)
[BingMaps/spatial-data-services/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/index?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-area.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/query-api/query-by-area.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-area?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-property.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/query-api/query-by-property.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-property?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-near-route.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/query-api/query-near-route.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-near-route?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-response-description.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/query-api/query-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-response-description?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/status-codes-and-error-handling.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/status-codes-and-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/status-codes-and-error-handling?branch=pr-en-us-248) |
[BingMaps/styling/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheets.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/code-optimizations-in-v8.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/articles/code-optimizations-in-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/code-optimizations-in-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/articles/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/map-keyboard-shortcuts?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/vector-map-labels.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/articles/vector-map-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/vector-map-labels?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/setting-map-control-parameters.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/creating-and-hosting-map-controls/setting-map-control-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/setting-map-control-pa [...]

2022-06-22 02:03 UTC, opbld33 commented
Docs Build status updates of commit _[62f95a2](https://github.com/AqMoh/bingmaps-docs/commits/62f95a240eb8efb21621e73beea1b140efd33eb8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/spatial-data-services/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/index?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-api-sample-code-vb?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-area.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/query-api/query-by-area.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-area?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-by-property.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/query-api/query-by-property.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-by-property?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-near-route.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/query-api/query-near-route.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-near-route?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/query-api/query-response-description.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/query-api/query-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/query-api/query-response-description?branch=pr-en-us-248) |
[BingMaps/spatial-data-services/status-codes-and-error-handling.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/spatial-data-services/status-codes-and-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/spatial-data-services/status-codes-and-error-handling?branch=pr-en-us-248) |
[BingMaps/styling/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/styling/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/index?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-entries.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/styling/map-style-sheet-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-entry-properties.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/styling/map-style-sheet-entry-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-extensions.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/styling/map-style-sheet-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-extensions?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheet-support.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/styling/map-style-sheet-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-support?branch=pr-en-us-248) |
[BingMaps/styling/map-style-sheets.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/styling/map-style-sheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/styling/map-style-sheets?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/code-optimizations-in-v8.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/articles/code-optimizations-in-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/code-optimizations-in-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/articles/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/articles/map-keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/map-keyboard-shortcuts?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/vector-map-labels.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/articles/vector-map-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/vector-map-labels?branch=pr-en-us-248) |
[BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/articles/zindexing-in-bing-maps-v8?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/customize-map-options-on-load-example?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/creating-and-hosting-map-controls/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/index?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/map-control-branches?branch=pr-en-us-248) |
[BingMaps/v8-web-control/creating-and-hosting-map-controls/setting-map-control-parameters.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-5-30/BingMaps/v8-web-control/creating-and-hosting-map-controls/setting-map-control-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/v8-web-control/creating-and-hosting-map-controls/setting-map-control-parameters?branch=pr-en-us-248) |
[BingMaps/v8-web- [...]

2022-06-22 02:12 UTC, AqMoh commented
@stevemunk
Had to sort out some merge conflicts, but should be good to go now. Thank you!!

2022-07-08 19:17 UTC, jmart1428 commented
@stevemunk  Are there any additional changes that you'd like to see in this PR? Thank you for your feedback!

2022-07-25 18:48 UTC, merged