[Bulk] Validation Fixes
MicrosoftDocs/bingmaps-docs pull request #254
Opened 2022-06-02 04:30 UTC by AqMoh

This PR fixes 59 issues.

2022-06-02 04:31 UTC, opbld32 commented
Docs Build status updates of commit _[56348fa](https://github.com/AqMoh/bingmaps-docs/commits/56348fa4fffd72f3f0070c73615292ec73980776)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/elevations/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) | [Details](#user-content-2d95feadf81c0ea779c87630c8df85c8-16d700b3)
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) | [Details](#user-content-4adc27bbff4fd19216e8e3aa4dc992d8-16d700b3)
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) | [Details](#user-content-cb7214718245a0600ae0a2a9b7f2b1af-16d700b3)
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-asynchronous-example?branch=pr-en-us-254) | [Details](#user-content-e58e292456c4713e4211251c84efed5e-16d700b3)
[BingMaps/rest-services/examples/optimized-waypoints-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/optimized-waypoints-example.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/optimized-waypoints-example?branch=pr-en-us-254) | [Details](#user-content-053280ebdec486934dd819ac686f4081-16d700b3)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) | [Details](#user-content-1a5ac4756804d137212780953e86ac60-16d700b3)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) | [Details](#user-content-1d31d5f02b9891549f2c42d90a7804d0-16d700b3)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) | [Details](#user-content-8ece3afb8fe714cba89c63a31eff4d74-16d700b3)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) | [Details](#user-content-29e2c2ae32a1cd6d2cf2713da28ed939-16d700b3)
[BingMaps/rest-services/developer-resources.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/developer-resources.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) | [Details](#user-content-279cb557ea5a6d3c53171130c71ab679-16d700b3)
[BingMaps/rest-services/getting-started-with-the-bing-maps-rest-services.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/getting-started-with-the-bing-maps-rest-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/getting-started-with-the-bing-maps-rest-services?branch=pr-en-us-254) | [Details](#user-content-88a274aab76457016e8435ac7288b074-16d700b3)
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-exa [...]

2022-06-02 04:56 UTC, opbld33 commented
Docs Build status updates of commit _[1bf0d0f](https://github.com/AqMoh/bingmaps-docs/commits/1bf0d0f4d3a0c487dcecad3f20c22b5dc6bf5a26)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) | [Details](#user-content-4adc27bbff4fd19216e8e3aa4dc992d8-aaafdb95)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) | [Details](#user-content-1a5ac4756804d137212780953e86ac60-aaafdb95)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) | [Details](#user-content-1d31d5f02b9891549f2c42d90a7804d0-aaafdb95)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) | [Details](#user-content-8ece3afb8fe714cba89c63a31eff4d74-aaafdb95)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) | [Details](#user-content-29e2c2ae32a1cd6d2cf2713da28ed939-aaafdb95)
[BingMaps/rest-services/examples/optimized-waypoints-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/optimized-waypoints-example.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/optimized-waypoints-example?branch=pr-en-us-254) | [Details](#user-content-053280ebdec486934dd819ac686f4081-aaafdb95)
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded [...]

2022-06-02 05:06 UTC, opbld31 commented
Docs Build status updates of commit _[f4c44a9](https://github.com/AqMoh/bingmaps-docs/commits/f4c44a9f64c4535ec8fadc0ad9e9b3599f0fc658)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) | [Details](#user-content-1a5ac4756804d137212780953e86ac60-4ff43f3c)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) | [Details](#user-content-1d31d5f02b9891549f2c42d90a7804d0-4ff43f3c)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) | [Details](#user-content-8ece3afb8fe714cba89c63a31eff4d74-4ff43f3c)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) | [Details](#user-content-29e2c2ae32a1cd6d2cf2713da28ed939-4ff43f3c)
[BingMaps/rest-services/examples/optimized-waypoints-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/optimized-waypoints-example.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/optimized-waypoints-example?branch=pr-en-us-254) | [Details](#user-content-053280ebdec486934dd819ac686f4081-4ff43f3c)
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us [...]

2022-06-02 05:16 UTC, opbld30 commented
Docs Build status updates of commit _[0e555c7](https://github.com/AqMoh/bingmaps-docs/commits/0e555c7760bf0395e215cb34438a48648b8aed05)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) | [Details](#user-content-1a5ac4756804d137212780953e86ac60-5051df79)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) | [Details](#user-content-1d31d5f02b9891549f2c42d90a7804d0-5051df79)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) | [Details](#user-content-8ece3afb8fe714cba89c63a31eff4d74-5051df79)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) | [Details](#user-content-29e2c2ae32a1cd6d2cf2713da28ed939-5051df79)
[BingMaps/rest-services/examples/optimized-waypoints-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/optimized-waypoints-example.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/optimized-waypoints-example?branch=pr-en-us-254) | [Details](#user-content-053280ebdec486934dd819ac686f4081-5051df79)
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us [...]

2022-06-02 05:26 UTC, opbld31 commented
Docs Build status updates of commit _[73a2064](https://github.com/AqMoh/bingmaps-docs/commits/73a20643cd33f8c5b9f50e348fb09b06056023a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) | [Details](#user-content-1a5ac4756804d137212780953e86ac60-8a77b419)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) | [Details](#user-content-1d31d5f02b9891549f2c42d90a7804d0-8a77b419)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) | [Details](#user-content-8ece3afb8fe714cba89c63a31eff4d74-8a77b419)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) | [Details](#user-content-29e2c2ae32a1cd6d2cf2713da28ed939-8a77b419)
[BingMaps/rest-services/examples/optimized-waypoints-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/optimized-waypoints-example.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/optimized-waypoints-example?branch=pr-en-us-254) | [Details](#user-content-053280ebdec486934dd819ac686f4081-8a77b419)
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us [...]

2022-06-02 05:32 UTC, opbld32 commented
Docs Build status updates of commit _[6858fab](https://github.com/AqMoh/bingmaps-docs/commits/6858fabc4011e26634b8a2a5e9bb24a5a6337444)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) | [Details](#user-content-1a5ac4756804d137212780953e86ac60-2e166b3d)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) | [Details](#user-content-1d31d5f02b9891549f2c42d90a7804d0-2e166b3d)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) | [Details](#user-content-8ece3afb8fe714cba89c63a31eff4d74-2e166b3d)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) | [Details](#user-content-29e2c2ae32a1cd6d2cf2713da28ed939-2e166b3d)
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/isochrone-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-example?branch=pr-en-us-254) | [...]

2022-06-02 14:48 UTC, MeeraDi commented on BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md
> +description: "This article outlines direct access the Bing Map tiles and how to add Bing Maps as a tile layer in a non-Bing Maps control."
This article outlines direct access to the Bing Map tiles and how to add Bing Maps as a tile layer in a non-Bing Map control.

2022-06-02 14:57 UTC, MeeraDi commented on BingMaps/rest-services/examples/driving-route-example.md
> +description: "The article provides a driving route example and shows how to request a driving route between two locations that minimizes the use of toll roads. Responses are shown for both XML and JS
Responses are shown for both XML and JSON.

2022-06-02 14:57 UTC, MeeraDi commented on BingMaps/rest-services/examples/distance-matrix-histogram-example.md
> +description: "This distance matrix histogram example returns a distance matrix histogram between a set of origins and destinations between a specific period of time."
for a specific period of time.

2022-06-02 14:59 UTC, MeeraDi commented on BingMaps/rest-services/examples/driving-route-with-route-path-example.md
> +description: "This example returns a driving route from the Minneapolis, Minnesota to St. Paul, Minnesota. Results are shown for both JSON and XML response formats."
This example returns a driving route from Minneapolis, Minnesota to St. Paul, Minnesota.

2022-06-02 15:01 UTC, MeeraDi commented on BingMaps/rest-services/examples/driving-route-with-route-path-example.md
> +This example returns a driving route from the Minneapolis, Minnesota to St. Paul, Minnesota. The route is optimized for distance and requests point values for the route’s path. Results are shown for
his example returns a driving route from Minneapolis, Minnesota to St. Paul, Minnesota.

2022-06-02 15:27 UTC, opbld33 commented
Docs Build status updates of commit _[7f784ea](https://github.com/AqMoh/bingmaps-docs/commits/7f784eadf51d95fe8034350696a68dd85f3bd7b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) | [Details](#user-content-1a5ac4756804d137212780953e86ac60-486f3e13)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) | [Details](#user-content-1d31d5f02b9891549f2c42d90a7804d0-486f3e13)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) | [Details](#user-content-8ece3afb8fe714cba89c63a31eff4d74-486f3e13)
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) | [Details](#user-content-29e2c2ae32a1cd6d2cf2713da28ed939-486f3e13)
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/isochrone-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-example?branch=pr-en-us-254) | [...]

2022-06-06 19:13 UTC, opbld33 commented
Docs Build status updates of commit _[93949b6](https://github.com/AqMoh/bingmaps-docs/commits/93949b6cc9cd24cbab2105f79b81b9168bb447c4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6c88beec)

<a id="6c88beec"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206061913070923-254/BuildReport?accessString=38394d4d4857be43804bc0b8665c99fcdf2f475c6f44fb3bf4cfdf4dfd3a3885).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-06 19:34 UTC, opbld33 commented
Docs Build status updates of commit _[c9a4abf](https://github.com/AqMoh/bingmaps-docs/commits/c9a4abf12af5326d866fd2d018933e21f7c310a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/isochrone-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/optimized-waypoints-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/optimized-waypoints-example.md) | :white_check_mark:Succeeded | [View [...]

2022-06-06 19:35 UTC, AqMoh commented
**Global effort to fix build validation errors**
@stevemunk 
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-13 21:55 UTC, opbld32 commented
Docs Build status updates of commit _[d214d2d](https://github.com/AqMoh/bingmaps-docs/commits/d214d2d9ba893258d0e1997882112266d1774c20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/isochrone-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/optimized-waypoints-example.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/examples/optimized-waypoints-example.md) | :white_check_mark:Succeeded | [View [...]

2022-06-14 00:56 UTC, stevemunk requested changes

2022-06-14 00:56 UTC, stevemunk commented on BingMaps/rest-services/getting-traffic-incident-data.md
> +## Traffic Incident Information Along a Route (Routes API)
```suggestion
## Traffic incident information along a route (Routes API)
```

2022-06-14 00:56 UTC, stevemunk commented on BingMaps/rest-services/getting-traffic-incident-data.md
> +## Traffic Incident Information within a Geographical Area (Traffic API)
```suggestion
## Traffic incident information within a geographical area (Traffic API)
```

2022-06-14 00:56 UTC, stevemunk commented on BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md
> +description: "This Type identifiers article lists top-level type IDs used by the Bing Maps APIs."
```suggestion
description: The overview page for the Type Identifiers section contains links to the top-level types used by the Bing Maps API including EatDrink, SeeDo, Shop, BanksAndCreditUnions, Hospitals, HotelsAndMotels and Parking.
```

2022-06-14 00:56 UTC, stevemunk commented on BingMaps/rest-services/developer-resources.md
> +description: "This article provides REST developer resources to learn more about Bing Maps, get your questions answered, and get the latest announcements."
```suggestion
description: This article provides links to Bing Maps REST developer resources such as forums, blogs, social media accounts and links to information on account issues and licensing questions.
```

2022-06-14 00:56 UTC, stevemunk commented on BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md
> +description: "This article outlines direct access to the Bing Map tiles and how to add Bing Maps as a tile layer in a non-Bing Maps control."
```suggestion
description: Learn how to access the Bing Map tiles directly to add Bing Maps as a tile layer in a non-Bing Maps control."
```

2022-06-14 00:56 UTC, stevemunk commented on BingMaps/rest-services/elevations/get-elevations.md
> +description: "This article provides URLs that let you get elevation values (in meters) for a set of locations, a polyline path, or area on the Earth."
```suggestion
description: "This article provides URLs that let you get elevation values (in meters) for a set of locations, a polyline path, or area on the Earth. This includes getting elevations for latitude and longitude coordinates, at equally-spaced locations along a polyline path or within a bounding box, getting the offset of the geoid sea level earth model from the ellipsoid earth model, also an explanation about elevations and coordinate values and working with earth models and zoom level." 
```

2022-06-14 00:56 UTC, stevemunk commented on BingMaps/rest-services/elevations/index.md
> +description: "Use the Bing Maps Elevations API to get elevation information for a set of locations, polyline, or area on the Earth."
```suggestion
description: The overview page for the Bing Maps Elevations API, used to get elevation information for a set of locations, polyline or area on the Earth, contains links to and descriptions of the elevations API.
```

2022-06-14 00:56 UTC, stevemunk commented on BingMaps/rest-services/elevations/point-compression-algorithm.md
> +description: "This article provides step-by-step instructions that describe the point compression algorithm, complete with an example."
```suggestion
description: This article provides step-by-step instructions that describe the point compression algorithm, complete with an example and instructions how to test your algorithm implementation.
```

2022-06-14 00:56 UTC, stevemunk commented on BingMaps/rest-services/examples/walking-route-example.md
> +description: "The example in this article returns a walking route from the Eiffel Tower to the Louvre Museum in Paris, France. Responses are shown for both XML and JSON formats."
```suggestion
description: "The example in this article returns a walking route from the Eiffel Tower to the Louvre Museum in Paris, France, optimized for distance. Responses are shown for both XML and JSON formats."
```

2022-06-16 19:25 UTC, stevemunk commented
@AqMoh Please let me know when you are finished making updates, thanks!

2022-06-22 02:27 UTC, opbld32 commented
Docs Build status updates of commit _[219a47a](https://github.com/AqMoh/bingmaps-docs/commits/219a47a50c1f00615979e26f528e1419229d3c30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/isochrone-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isoc [...]

2022-06-22 02:28 UTC, opbld30 commented
Docs Build status updates of commit _[a2b7003](https://github.com/AqMoh/bingmaps-docs/commits/a2b7003bbac24eb5c51f9d643b4b124475d95e2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/isochrone-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isoc [...]

2022-06-22 02:29 UTC, opbld32 commented
Docs Build status updates of commit _[3dc6ab7](https://github.com/AqMoh/bingmaps-docs/commits/3dc6ab75888edaa6cfa21783ea59f2ece9a7b0c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/isochrone-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isoc [...]

2022-06-22 02:30 UTC, opbld30 commented
Docs Build status updates of commit _[47e05ff](https://github.com/AqMoh/bingmaps-docs/commits/47e05ff19b535f2dd4c118d6b0ed1c34b7f9f690)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/isochrone-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isoc [...]

2022-06-22 02:30 UTC, AqMoh commented
@stevemunk 
Changes implemented, save for suggestions that have been marked as outdated. Please let me know if this is good to go, thank you!

2022-06-22 02:31 UTC, opbld32 commented
Docs Build status updates of commit _[f10c5a8](https://github.com/AqMoh/bingmaps-docs/commits/f10c5a8656c8b865ba8e766367262349d01a8d47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/isochrone-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isoc [...]

2022-06-22 02:33 UTC, opbld33 commented
Docs Build status updates of commit _[e03af89](https://github.com/AqMoh/bingmaps-docs/commits/e03af890eb587ba117a4ba31edfa295dc96453ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/supported-culture-codes?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/eat-drink-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/index?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/see-do-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/type-identifiers/shop-types?branch=pr-en-us-254) |
[BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-parameters-and-types/user-context-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-parameters-and-types/user-context-parameters?branch=pr-en-us-254) |
[BingMaps/rest-services/common-response-description.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/common-response-description.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/common-response-description?branch=pr-en-us-254) |
[BingMaps/rest-services/developer-resources.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/developer-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/developer-resources?branch=pr-en-us-254) |
[BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/directly-accessing-the-bing-maps-tiles?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/elevation-data.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/elevation-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/elevation-data?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/get-elevations.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/get-elevations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/get-elevations?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/index?branch=pr-en-us-254) |
[BingMaps/rest-services/elevations/point-compression-algorithm.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/elevations/point-compression-algorithm.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/elevations/point-compression-algorithm?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/distance-matrix-histogram-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/distance-matrix-histogram-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/distance-matrix-histogram-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-using-tolerances-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-using-tolerances-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-using-tolerances-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/driving-route-with-route-path-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/driving-route-with-route-path-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/driving-route-with-route-path-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-asynchronous-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/isochrone-asynchronous-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isochrone-asynchronous-example?branch=pr-en-us-254) |
[BingMaps/rest-services/examples/isochrone-example.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-90/BingMaps/rest-services/examples/isochrone-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/examples/isoc [...]

2022-07-08 18:33 UTC, closed without merging