[Bulk] Validation Fixes
MicrosoftDocs/bingmaps-docs pull request #258
Opened 2022-06-03 01:27 UTC by AqMoh

This PR fixes issues

2022-06-03 01:43 UTC, opbld30 commented
Docs Build status updates of commit _[4ac03a6](https://github.com/AqMoh/bingmaps-docs/commits/4ac03a65e7429dcfdec2af130ef607697b429e5f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0c311555)

<a id="0c311555"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206030143053558-258/BuildReport?accessString=c1aadcbc40db0be98fa431176d19fd7ed1bb4166ced817f428c82fd6e688371d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 17:12 UTC, opbld31 commented
Docs Build status updates of commit _[25a3ffc](https://github.com/AqMoh/bingmaps-docs/commits/25a3ffc695ce05a0c3cc320912fe80951852eedb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-258) | [Details](#user-content-dd6780c4dc1f8888e8e2ae239cf015fd-dc21d3f9)
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-258) | [Details](#user-content-6f117dbd61f09b2f20031fb6705694d2-dc21d3f9)
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-258) | [Details](#user-content-1de30c63f70fad7f4790986e292e2eee-dc21d3f9)
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-258) | [Details](#user-content-26c684c29ccab0019cc0baa619a657c3-dc21d3f9)
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-258) | [Details](#user-content-178982884c362d5c3e078e519108d8d4-dc21d3f9)
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-258) | [Details](#user-content-98178e63f037961d85672290a0a022ad-dc21d3f9)
[BingMaps/rest-services/routes/maneuver-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/maneuver-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/maneuver-types?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/route-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/route-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/route-data?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/snap-points-to-roads.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/snap-points-to-roads.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/snap-points-to-roads?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/snap-to-road-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/snap-to-road-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/snap-to-road-data?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/warning-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/warning-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/warning-types?branch=pr-en-us-258) |
[BingMaps/rest-services/status-codes-and-error-handling.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/status-codes-and-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/status-codes-and-error-handling?branch=pr-en-us-258) |
[BingMaps/rest-services/traffic/get-traffic-incidents.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/traffic/get-traffic-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/traffic/get-traffic-incidents?branch=pr-en-us-258) |
[BingMaps/rest-services/traffic/traffic-incident-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/traffic/traffic-incident-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/traffic/traffic-incident-data?branch=pr-en-us-258) |
[BingMaps/rest-services/using-the-rest-services-with-net.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/using-the-rest-services-with-net.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/using-the-rest-services-with-net?branch=pr-en-us-258) |
[BingMaps/sdk-native/getting-started-ios/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/getting-started-ios/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/getting-started-ios/index?branch=pr-en-us-258) |
[BingMaps/sdk-native/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/index?branch=pr-en-us-258) |

<a id="dd6780c4dc1f8888e8e2ae239cf015fd-dc21d3f9"></a>
### [BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md)
 - **Line 13, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'v-chrfr' is not a valid Microsoft alias.`````

<a id="6f117dbd61f09b2f20031fb6705694d2-dc21d3f9"></a>
### [BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md)
 - **Line 12, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'v-chrfr' is not a valid Microsoft alias.`````

<a id="1de30c63f70fad7f4790986e292e2eee-dc21d3f9"></a>
### [BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md)
 - **Line 12, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'v-chrfr' is not a valid Microsoft alias.`````

<a id="26c684c29ccab0019cc0baa619a657c3-dc21d3f9"></a>
### [BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md)
 - **Line 12, Column 12**: **[Suggestion: ms-author-invalid -  [...]

2022-06-03 18:18 UTC, jmart1428 commented on BingMaps/rest-services/routes/maneuver-types.md
> +description: "This article lists maneuver type values thar are returned the Routes in the maneuverType field in the HTTP response."
typo
thar = that

2022-06-03 18:21 UTC, jmart1428 commented on BingMaps/rest-services/routes/snap-to-road-data.md
> +description: "The response returned by the Snap to Road API contains either an SnapToRoadResponse resource, which contains the snapped point data, or an RouteProxyAsyncStatus resource. This article s
Too long per https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/description-missing?branch=main

2022-06-03 18:23 UTC, jmart1428 commented on BingMaps/rest-services/timezone/index.md
> +description: "The Bing Maps Time Zone API makes it easy to find a time zone and daylight savings time for a location by query or latitude and longitude coordinates. This article provides a table of r
Too long per https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/description-missing?branch=main

2022-06-03 18:23 UTC, jmart1428 commented on BingMaps/rest-services/timezone/list-time-zones.md
> +description: "The Time Zone API list operation returns a complete list of time zone information for either the Microsoft Windows or IANA Time Zone standard. This article provides API templates, param
Too long per https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/description-missing?branch=main

2022-06-03 18:24 UTC, jmart1428 commented on BingMaps/rest-services/traffic/traffic-incident-data.md
> +description: "The response returned by a Traffic URL contains one or more TrafficIncident resources. This article contains a table that describes the fields in the traffic incident resource. JSON and
Too long per https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/description-missing?branch=main

2022-06-05 15:35 UTC, opbld32 commented
Docs Build status updates of commit _[b56fd4f](https://github.com/AqMoh/bingmaps-docs/commits/b56fd4f79b6f916bffb0ebcc114cf4f7735862f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary-data?branch=pr-en-us-258) | [Details](#user-content-dd6780c4dc1f8888e8e2ae239cf015fd-ae9f6f6a)
[BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/convert-local-time-zone?branch=pr-en-us-258) | [Details](#user-content-6f117dbd61f09b2f20031fb6705694d2-ae9f6f6a)
[BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/find-time-zone?branch=pr-en-us-258) | [Details](#user-content-1de30c63f70fad7f4790986e292e2eee-ae9f6f6a)
[BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/index?branch=pr-en-us-258) | [Details](#user-content-26c684c29ccab0019cc0baa619a657c3-ae9f6f6a)
[BingMaps/rest-services/timezone/list-time-zones.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/list-time-zones.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/list-time-zones?branch=pr-en-us-258) | [Details](#user-content-178982884c362d5c3e078e519108d8d4-ae9f6f6a)
[BingMaps/rest-services/timezone/time-zone-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/time-zone-data.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/timezone/time-zone-data?branch=pr-en-us-258) | [Details](#user-content-98178e63f037961d85672290a0a022ad-ae9f6f6a)
[BingMaps/rest-services/routes/maneuver-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/maneuver-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/maneuver-types?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/optimized-itinerary.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/optimized-itinerary?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/route-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/route-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/route-data?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/snap-points-to-roads.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/snap-points-to-roads.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/snap-points-to-roads?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/snap-to-road-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/snap-to-road-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/snap-to-road-data?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/warning-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/warning-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/warning-types?branch=pr-en-us-258) |
[BingMaps/rest-services/status-codes-and-error-handling.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/status-codes-and-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/status-codes-and-error-handling?branch=pr-en-us-258) |
[BingMaps/rest-services/traffic/get-traffic-incidents.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/traffic/get-traffic-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/traffic/get-traffic-incidents?branch=pr-en-us-258) |
[BingMaps/rest-services/traffic/traffic-incident-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/traffic/traffic-incident-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/traffic/traffic-incident-data?branch=pr-en-us-258) |
[BingMaps/rest-services/using-the-rest-services-with-net.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/using-the-rest-services-with-net.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/using-the-rest-services-with-net?branch=pr-en-us-258) |
[BingMaps/sdk-native/getting-started-ios/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/getting-started-ios/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/getting-started-ios/index?branch=pr-en-us-258) |
[BingMaps/sdk-native/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/index?branch=pr-en-us-258) |

<a id="dd6780c4dc1f8888e8e2ae239cf015fd-ae9f6f6a"></a>
### [BingMaps/rest-services/routes/optimized-itinerary-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/optimized-itinerary-data.md)
 - **Line 13, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'v-chrfr' is not a valid Microsoft alias.`````

<a id="6f117dbd61f09b2f20031fb6705694d2-ae9f6f6a"></a>
### [BingMaps/rest-services/timezone/convert-local-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/convert-local-time-zone.md)
 - **Line 12, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'v-chrfr' is not a valid Microsoft alias.`````

<a id="1de30c63f70fad7f4790986e292e2eee-ae9f6f6a"></a>
### [BingMaps/rest-services/timezone/find-time-zone.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/find-time-zone.md)
 - **Line 12, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'v-chrfr' is not a valid Microsoft alias.`````

<a id="26c684c29ccab0019cc0baa619a657c3-ae9f6f6a"></a>
### [BingMaps/rest-services/timezone/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/timezone/index.md)
 - **Line 12, Column 12**: **[Suggestion: ms-author-invalid -  [...]

2022-06-13 16:23 UTC, AqMoh commented
**Global effort to fix build validation errors**
@stevemunk 
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-13 23:56 UTC, stevemunk requested changes

2022-06-13 23:56 UTC, stevemunk commented on BingMaps/rest-services/status-codes-and-error-handling.md
> +## Handling Empty Responses
The capitalization in headers is wrong all over the place in the Bing Maps Docs See [here](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=28718) "Microsoft style uses sentence-style capitalization. That means everything is lowercase except the first word of a sentence "

```suggestion
## Handling empty responses
```

2022-06-13 23:56 UTC, stevemunk commented on BingMaps/rest-services/traffic/get-traffic-incidents.md
> +description: "This article provides a URL template to request traffic incident information. Template parameters and examples are provided."
```suggestion
description: "This article describes how to get traffic incidents and provides a URL template to request traffic incident information. Template parameters and examples are provided."
```

2022-06-13 23:56 UTC, stevemunk commented on BingMaps/rest-services/traffic/traffic-incident-data.md
> +description: "This article contains a table that describes the fields in the traffic incident resource. JSON and XML formats are shown."
```suggestion
description: This article describes the Traffic Incident Data contained in TrafficIncident resources, returned by a Traffic URL, in a table that describes each field. Both JSON and XML formats are shown.
```

2022-06-13 23:56 UTC, stevemunk commented on BingMaps/rest-services/using-the-rest-services-with-net.md
> +description: "This article describes how to interact with the Bing Maps REST Services APIs using .NET, covering making requests, implementing requents, and data contracts."
```suggestion
description: "This article describes how to interact with the Bing Maps REST Services APIs using .NET, covering making use of sessions, making and implementing requests, and data contracts, includes sample code"
```

2022-06-13 23:56 UTC, stevemunk commented on BingMaps/sdk-native/getting-started-ios/index.md
> +description: "This article is a tutorial that goes through creating an iOS app with a Bing Maps Native Control step-by-step."
```suggestion
description: The getting started with iOS article is a tutorial that steps through creating an iOS app with a Bing Maps Native Control.
```

2022-06-13 23:56 UTC, stevemunk commented on BingMaps/sdk-native/index.md
> +description: "This article outlines Bing Maps SDK for Android and iOS, listing resources on how to get started, map control concepts, map control API reference, and map services API reference."
```suggestion
description: The overview page for the Bing Maps SDK for Android and iOS section contains links to information about Bing Maps keys, license and terms of service and to the different topics covered such as getting started with Android and iOS, map control concepts and map control and services API references.
```

2022-06-16 19:40 UTC, stevemunk commented
@AqMoh Please let me know when you are ready for a final review. thank you

2022-06-17 17:22 UTC, opbld30 commented
Docs Build status updates of commit _[a62c5e7](https://github.com/AqMoh/bingmaps-docs/commits/a62c5e7d1a4fff0c1cf493073d237e60215ecfb3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/routes/maneuver-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/maneuver-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/maneuver-types?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/route-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/route-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/route-data?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/snap-points-to-roads.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/snap-points-to-roads.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/snap-points-to-roads?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/snap-to-road-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/snap-to-road-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/snap-to-road-data?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/warning-types.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/routes/warning-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/warning-types?branch=pr-en-us-258) |
[BingMaps/rest-services/status-codes-and-error-handling.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/status-codes-and-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/status-codes-and-error-handling?branch=pr-en-us-258) |
[BingMaps/rest-services/traffic/get-traffic-incidents.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/traffic/get-traffic-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/traffic/get-traffic-incidents?branch=pr-en-us-258) |
[BingMaps/rest-services/traffic/traffic-incident-data.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/traffic/traffic-incident-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/traffic/traffic-incident-data?branch=pr-en-us-258) |
[BingMaps/rest-services/using-the-rest-services-with-net.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/rest-services/using-the-rest-services-with-net.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/using-the-rest-services-with-net?branch=pr-en-us-258) |
[BingMaps/sdk-native/getting-started-ios/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/getting-started-ios/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/getting-started-ios/index?branch=pr-en-us-258) |
[BingMaps/sdk-native/index.md](https://github.com/MicrosoftDocs/bingmaps-docs/blob/main/BingMaps/sdk-native/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/index?branch=pr-en-us-258) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206171721026997-258/BuildReport?accessString=fb82e3264e28074b3a4a2aeb02fbd730024da67704b367c55915a5685ba96bdb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-17 17:31 UTC, AqMoh commented
@stevemunk 
Requests have been incorporated. Please provide your review--thank you!

2022-06-17 21:35 UTC, stevemunk commented
@AqMoh Some of the requested changes didn't get saved. I've unresolved a few of them. If you didn't make the requested changes because you don't agree with my feedback, that's fine, you might be right, but let's discuss.  Thanks!

2022-06-22 02:33 UTC, AqMoh commented
@stevemunk 
Hi Steve! Your suggestions, on my end, are labeled as outdated and I am unable to commit/push them. Is this because the file has already been worked on by someone else?

2022-06-22 14:14 UTC, stevemunk commented
@AqMoh Most likely. Have you synced your branch with main?

2022-06-22 14:19 UTC, opbld33 commented
Docs Build status updates of commit _[f39edf0](https://github.com/AqMoh/bingmaps-docs/commits/f39edf031eb057930d3297aff4787b034ccda788)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/rest-services/routes/maneuver-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/routes/maneuver-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/maneuver-types?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/route-data.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/routes/route-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/route-data?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/snap-points-to-roads.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/routes/snap-points-to-roads.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/snap-points-to-roads?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/snap-to-road-data.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/routes/snap-to-road-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/snap-to-road-data?branch=pr-en-us-258) |
[BingMaps/rest-services/routes/warning-types.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/routes/warning-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/routes/warning-types?branch=pr-en-us-258) |
[BingMaps/rest-services/status-codes-and-error-handling.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/status-codes-and-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/status-codes-and-error-handling?branch=pr-en-us-258) |
[BingMaps/rest-services/traffic/get-traffic-incidents.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/traffic/get-traffic-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/traffic/get-traffic-incidents?branch=pr-en-us-258) |
[BingMaps/rest-services/traffic/traffic-incident-data.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/traffic/traffic-incident-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/traffic/traffic-incident-data?branch=pr-en-us-258) |
[BingMaps/rest-services/using-the-rest-services-with-net.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/rest-services/using-the-rest-services-with-net.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/rest-services/using-the-rest-services-with-net?branch=pr-en-us-258) |
[BingMaps/sdk-native/getting-started-ios/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/sdk-native/getting-started-ios/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/getting-started-ios/index?branch=pr-en-us-258) |
[BingMaps/sdk-native/index.md](https://github.com/AqMoh/bingmaps-docs/blob/validation-am-bingmaps-141/BingMaps/sdk-native/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/BingMaps/sdk-native/index?branch=pr-en-us-258) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202206221417598491-258/BuildReport?accessString=4232e71cad443b1ec7af96ae727547e95454240348673d989eccad490ca703e6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 20:28 UTC, jmart1428 commented
@stevemunk #please-close

2022-07-20 21:45 UTC, closed without merging