[Bulk] Broken Link fixes
MicrosoftDocs/bingmaps-docs pull request #300
Opened 2022-11-07 20:29 UTC by DhurataJ

Fix/remove broken links

2022-11-07 20:31 UTC, opbld32 commented
Learn Build status updates of commit _[725034f](https://github.com/DhurataJ/bingmaps-docs/commits/725034fe01d03b266f8b8ec9359ec207e5938360)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php?branch=pr-en-us-300) |
[BingMaps/coverage/transit-coverage/africa.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/africa.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/africa?branch=pr-en-us-300) |
[BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/google-maps-to-bing-maps-migration-guide?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps?branch=pr-en-us-300) |
[BingMaps/getting-started/index.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/index?branch=pr-en-us-300) |
[BingMaps/retired/navteq-poi-entity-types.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/navteq-poi-entity-types.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/navteq-poi-entity-types?branch=pr-en-us-300) |
[BingMaps/retired/traffic-coverage-old.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/traffic-coverage-old.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/traffic-coverage-old?branch=pr-en-us-300) |
[BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/delete-data-source?branch=pr-en-us-300) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202211072029499263-300/BuildReport?accessString=7b4d0c40f6e7f9385a4fe742786ba67e8bb031269a2d02f73453735275b3d02f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 20:37 UTC, opbld33 commented
Learn Build status updates of commit _[35a0eba](https://github.com/DhurataJ/bingmaps-docs/commits/35a0eba34a25576d5cdc08b4b50bb2678da01475)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php?branch=pr-en-us-300) |
[BingMaps/coverage/transit-coverage/africa.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/africa.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/africa?branch=pr-en-us-300) |
[BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/google-maps-to-bing-maps-migration-guide?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps?branch=pr-en-us-300) |
[BingMaps/getting-started/index.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/index?branch=pr-en-us-300) |
[BingMaps/retired/navteq-poi-entity-types.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/navteq-poi-entity-types.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/navteq-poi-entity-types?branch=pr-en-us-300) |
[BingMaps/retired/traffic-coverage-old.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/traffic-coverage-old.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/traffic-coverage-old?branch=pr-en-us-300) |
[BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/delete-data-source?branch=pr-en-us-300) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202211072035491345-300/BuildReport?accessString=9251f2fc103d3b3151bf4539fae23672ce4746630c268c6cd4017f5769c11999).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 20:40 UTC, DhurataJ commented
**Global effort to fix broken links**

@stevemunk 

The C+E Skilling team is fixing broken links on learn.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. I'd very much appreciate your timely review and feedback on the link changes I've suggested. Thanks!

2022-12-12 17:36 UTC, stevemunk requested changes
Please use secure links where possible.

2022-12-12 17:36 UTC, stevemunk commented on BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md
>  |Kolkata|[SBSTC](http://sbstc.co.in/)
This link goes to a page that only shows: 

> Welcome to test page

2022-12-12 17:36 UTC, stevemunk commented on BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md
>  |Mumbai|[Mumbai Metropolitan Region Development Authority](http://mmrda.maharashtra.gov.in/home)
```suggestion
|Mumbai|[Mumbai Metropolitan Region Development Authority](https://mmrda.maharashtra.gov.in/home) 

```

2022-12-12 17:36 UTC, stevemunk commented on BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md
>  |New Delhi|[Delhi Metro Rail Corporation](http://www.delhimetrorail.com)
```suggestion
|New Delhi|[Delhi Metro Rail Corporation](https://www.delhimetrorail.com) 

```

2022-12-12 17:36 UTC, stevemunk commented on BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md
>  |New Delhi|[Rapid MetroRail Gurgaon Limited](http://www.rapidmetrogurgaon.com)
```suggestion
|New Delhi|[Rapid MetroRail Gurgaon Limited](https://www.rapidmetrogurgaon.com) 

```

2022-12-12 17:36 UTC, stevemunk commented on BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md
> +|Gunma|[Nagai Transport Co., Ltd.](http://www.nagai-unyu.net/)
```suggestion
|Gunma|[Nagai Transport Co., Ltd.](https://www.nagai-unyu.net/)  

```

2022-12-12 17:36 UTC, stevemunk commented on BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md
>  |Yamanashi|[南アルプス市](http://www.city.minami-alps.yamanashi.jp/)
```suggestion
|Yamanashi|[南アルプス市](https://www.city.minami-alps.yamanashi.jp/) 

```

2022-12-12 18:20 UTC, opbld33 commented
Learn Build status updates of commit _[12d56f2](https://github.com/DhurataJ/bingmaps-docs/commits/12d56f226b313d5a141303648048ba68bf6aa01d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands?branch=pr-en-us-300) | [Details](#user-content-1371faaadc4505823b4b92559c3669aa-0ae95732)
[BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php?branch=pr-en-us-300) |
[BingMaps/coverage/transit-coverage/africa.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/africa.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/africa?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/google-maps-to-bing-maps-migration-guide?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps?branch=pr-en-us-300) |
[BingMaps/getting-started/index.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/index?branch=pr-en-us-300) |
[BingMaps/retired/navteq-poi-entity-types.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/navteq-poi-entity-types.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/navteq-poi-entity-types?branch=pr-en-us-300) |
[BingMaps/retired/traffic-coverage-old.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/traffic-coverage-old.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/traffic-coverage-old?branch=pr-en-us-300) |
[BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/delete-data-source?branch=pr-en-us-300) |

<a id="1371faaadc4505823b4b92559c3669aa-0ae95732"></a>
### [BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md)
 - **Line 351, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 356, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202212121818299730-300/BuildReport?accessString=0c3e8b06202562709ada3389015e6bec0720f0302b483828fa658f477e4a2b19).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-12 18:23 UTC, opbld33 commented
Learn Build status updates of commit _[82227c7](https://github.com/DhurataJ/bingmaps-docs/commits/82227c70302588774a30b81cc18e717fd40417a7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands?branch=pr-en-us-300) | [Details](#user-content-1371faaadc4505823b4b92559c3669aa-e5a2ee40)
[BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php?branch=pr-en-us-300) |
[BingMaps/coverage/transit-coverage/africa.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/africa.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/africa?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/google-maps-to-bing-maps-migration-guide?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps?branch=pr-en-us-300) |
[BingMaps/getting-started/index.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/index?branch=pr-en-us-300) |
[BingMaps/retired/navteq-poi-entity-types.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/navteq-poi-entity-types.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/navteq-poi-entity-types?branch=pr-en-us-300) |
[BingMaps/retired/traffic-coverage-old.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/traffic-coverage-old.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/traffic-coverage-old?branch=pr-en-us-300) |
[BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/delete-data-source?branch=pr-en-us-300) |

<a id="1371faaadc4505823b4b92559c3669aa-e5a2ee40"></a>
### [BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md)
 - **Line 252, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 268, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 273, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 290, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 294, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 358, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 363, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202212121821117605-300/BuildReport?accessString=ac327686e2d22c2500510222fa083d8804ef7c0cce8161970cd6aa856fc050ca).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-12 20:21 UTC, opbld30 commented
Learn Build status updates of commit _[83a47c7](https://github.com/DhurataJ/bingmaps-docs/commits/83a47c79c5aa7b3b28a8268f15b8b917d1afebba)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands?branch=pr-en-us-300) | [Details](#user-content-1371faaadc4505823b4b92559c3669aa-a02d5f4b)
[BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php?branch=pr-en-us-300) |
[BingMaps/coverage/transit-coverage/africa.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/africa.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/africa?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/google-maps-to-bing-maps-migration-guide?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps?branch=pr-en-us-300) |
[BingMaps/getting-started/index.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/index?branch=pr-en-us-300) |
[BingMaps/retired/navteq-poi-entity-types.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/navteq-poi-entity-types.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/navteq-poi-entity-types?branch=pr-en-us-300) |
[BingMaps/retired/traffic-coverage-old.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/traffic-coverage-old.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/traffic-coverage-old?branch=pr-en-us-300) |
[BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/delete-data-source?branch=pr-en-us-300) |

<a id="1371faaadc4505823b4b92559c3669aa-a02d5f4b"></a>
### [BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md)
 - **Line 252, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 268, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 273, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 290, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 294, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 358, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 363, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202212122019243421-300/BuildReport?accessString=a61455102fb5a2fdd6e9b43c26d9d948da355e9ed05b244e72776168fc6d9ee4).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-12 23:02 UTC, stevemunk requested changes
I made comments on several of the `http` (not secure) links... Please make changes as needed then go through the rest `http` links and test each one in a browser after adding the 's' (`https`). If it works, change the link to `https`. If it doesn't work, make sure the original link (`http`) works and if so, leave it as it. If it doesn't work, please remove the link. Once done I will approve and merge into main.

2022-12-13 14:22 UTC, opbld30 commented
Learn Build status updates of commit _[94cea19](https://github.com/DhurataJ/bingmaps-docs/commits/94cea19cc07d7891d2d2caa3db2091df7991e642)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands?branch=pr-en-us-300) | [Details](#user-content-1371faaadc4505823b4b92559c3669aa-55520e17)
[BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php?branch=pr-en-us-300) |
[BingMaps/coverage/transit-coverage/africa.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/africa.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/africa?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/google-maps-to-bing-maps-migration-guide?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps?branch=pr-en-us-300) |
[BingMaps/getting-started/index.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/index?branch=pr-en-us-300) |
[BingMaps/retired/navteq-poi-entity-types.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/navteq-poi-entity-types.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/navteq-poi-entity-types?branch=pr-en-us-300) |
[BingMaps/retired/traffic-coverage-old.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/traffic-coverage-old.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/traffic-coverage-old?branch=pr-en-us-300) |
[BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/delete-data-source?branch=pr-en-us-300) |

<a id="1371faaadc4505823b4b92559c3669aa-55520e17"></a>
### [BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md)
 - **Line 252, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 268, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 273, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 290, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 298, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 357, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 362, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 365, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 368, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202212131421204464-300/BuildReport?accessString=77afe1bb9f542077598eee50358701c9db516c8b29f3fb2c84020140f41543f6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post [...]

2022-12-13 14:24 UTC, opbld31 commented
Learn Build status updates of commit _[96ea1a9](https://github.com/DhurataJ/bingmaps-docs/commits/96ea1a93b8eaa37d03ba6fc286e66662b31bb1f7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands?branch=pr-en-us-300) | [Details](#user-content-1371faaadc4505823b4b92559c3669aa-fa49f855)
[BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php?branch=pr-en-us-300) |
[BingMaps/coverage/transit-coverage/africa.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/africa.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/africa?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/google-maps-to-bing-maps-migration-guide?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps?branch=pr-en-us-300) |
[BingMaps/getting-started/index.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/index?branch=pr-en-us-300) |
[BingMaps/retired/navteq-poi-entity-types.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/navteq-poi-entity-types.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/navteq-poi-entity-types?branch=pr-en-us-300) |
[BingMaps/retired/traffic-coverage-old.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/traffic-coverage-old.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/traffic-coverage-old?branch=pr-en-us-300) |
[BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/delete-data-source?branch=pr-en-us-300) |

<a id="1371faaadc4505823b4b92559c3669aa-fa49f855"></a>
### [BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md)
 - **Line 252, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 268, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 273, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 290, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 298, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 357, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 362, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 365, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 368, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202212131421431768-300/BuildReport?accessString=72b989557d6ed284a410e3f57ea5b35606a62ac2b5372f5c35668446391a5f0a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post [...]

2022-12-13 14:53 UTC, opbld32 commented
Learn Build status updates of commit _[3540574](https://github.com/DhurataJ/bingmaps-docs/commits/3540574e5b2c2a0663a182c87922e7bc3540232b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands?branch=pr-en-us-300) | [Details](#user-content-1371faaadc4505823b4b92559c3669aa-90529554)
[BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php?branch=pr-en-us-300) |
[BingMaps/coverage/transit-coverage/africa.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/africa.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/africa?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/google-maps-to-bing-maps-migration-guide?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps?branch=pr-en-us-300) |
[BingMaps/getting-started/index.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/index?branch=pr-en-us-300) |
[BingMaps/retired/navteq-poi-entity-types.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/navteq-poi-entity-types.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/navteq-poi-entity-types?branch=pr-en-us-300) |
[BingMaps/retired/traffic-coverage-old.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/traffic-coverage-old.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/traffic-coverage-old?branch=pr-en-us-300) |
[BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/delete-data-source?branch=pr-en-us-300) |

<a id="1371faaadc4505823b4b92559c3669aa-90529554"></a>
### [BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md)
 - **Line 252, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 268, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 273, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 290, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 298, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 357, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 362, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 365, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 368, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202212131451598269-300/BuildReport?accessString=456e1d5d1a7c497e99b06815a4c044cc39a2684fd03fe1f42ef6c7c1c555a5b3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post [...]

2022-12-13 18:44 UTC, opbld31 commented
Learn Build status updates of commit _[64ee84d](https://github.com/DhurataJ/bingmaps-docs/commits/64ee84d0e2f5f3e37467758d697e98e469afdca9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands?branch=pr-en-us-300) | [Details](#user-content-1371faaadc4505823b4b92559c3669aa-ea97acf8)
[BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php?branch=pr-en-us-300) |
[BingMaps/coverage/transit-coverage/africa.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/africa.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/africa?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/google-maps-to-bing-maps-migration-guide?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps?branch=pr-en-us-300) |
[BingMaps/getting-started/index.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/index?branch=pr-en-us-300) |
[BingMaps/retired/navteq-poi-entity-types.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/navteq-poi-entity-types.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/navteq-poi-entity-types?branch=pr-en-us-300) |
[BingMaps/retired/traffic-coverage-old.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/traffic-coverage-old.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/traffic-coverage-old?branch=pr-en-us-300) |
[BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/delete-data-source?branch=pr-en-us-300) |

<a id="1371faaadc4505823b4b92559c3669aa-ea97acf8"></a>
### [BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md)
 - **Line 252, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 268, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 273, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 290, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 298, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 357, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 362, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 365, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 368, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202212131842591216-300/BuildReport?accessString=d417eceece99cad67315ad35d0e8f52b183441a71532f014e71ddb3ccf642f09).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post [...]

2022-12-13 21:23 UTC, v-emilypr commented on BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md
>  |Taipei|[永和區公所](http://www.yonghe.ntpc.gov.tw)
This is updated to https.

2022-12-13 21:50 UTC, opbld30 commented
Learn Build status updates of commit _[b3df0f2](https://github.com/DhurataJ/bingmaps-docs/commits/b3df0f28ae67f0d8d687fee600f25449161a93a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/articles/accessing-the-bing-spatial-data-services-using-php?branch=pr-en-us-300) |
[BingMaps/coverage/transit-coverage/africa.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/africa.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/africa?branch=pr-en-us-300) |
[BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/coverage/transit-coverage/asia-australia-pacific-islands?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/Google-Maps-to-Bing-Maps-Migration-Guide.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/google-maps-to-bing-maps-migration-guide?branch=pr-en-us-300) |
[BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/google-maps-to-bing-maps-migration-guide/why-bing-maps?branch=pr-en-us-300) |
[BingMaps/getting-started/index.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/getting-started/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/getting-started/index?branch=pr-en-us-300) |
[BingMaps/retired/navteq-poi-entity-types.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/navteq-poi-entity-types.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/navteq-poi-entity-types?branch=pr-en-us-300) |
[BingMaps/retired/traffic-coverage-old.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/retired/traffic-coverage-old.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/retired/traffic-coverage-old?branch=pr-en-us-300) |
[BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md](https://github.com/DhurataJ/bingmaps-docs/blob/dhj-bingmaps-docs-wb1/BingMaps/spatial-data-services/data-source-management-api/delete-data-source.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/BingMaps/spatial-data-services/data-source-management-api/delete-data-source?branch=pr-en-us-300) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/587a3825-77bd-8a4b-21c8-e8662dbef49c/202212132149160939-300/BuildReport?accessString=0aa1384f1e2a2bb0c19fd702d21d80ed382770babe20341c0316695fb6092c8c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/587a3825-77bd-8a4b-21c8-e8662dbef49c?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-15 19:36 UTC, stevemunk approved these changes

2022-12-15 19:36 UTC, merged